"""
This type stub file was generated by pyright.
"""

from . import buffer, crust, crustslices, dispatcher, document, editor, editwindow, filling, frame, images, interpreter, introspect, pseudo, shell, sliceshell, version

"""The py package, formerly the PyCrust package."""
__author__ = ...
