"""
This type stub file was generated by pyright.
"""

"""Buffer class."""
__author__ = ...
class Buffer:
    """Buffer class."""
    id = ...
    def __init__(self, filename=...) -> None:
        """Create a Buffer instance."""
        ...
    
    def addEditor(self, editor): # -> None:
        """Add an editor."""
        ...
    
    def hasChanged(self): # -> Literal[False]:
        """Return True if text in editor has changed since last save."""
        ...
    
    def new(self, filepath): # -> None:
        """New empty buffer."""
        ...
    
    def open(self, filename): # -> None:
        """Open file into buffer."""
        ...
    
    def overwriteConfirm(self, filepath): # -> Literal[False]:
        """Confirm overwriting an existing file."""
        ...
    
    def save(self): # -> None:
        """Save buffer."""
        ...
    
    def saveAs(self, filename): # -> None:
        """Save buffer."""
        ...
    
    def updateNamespace(self): # -> bool:
        """Update the namespace for autocompletion and calltips.

        Return True if updated, False if there was an error."""
        ...
    


