"""
This type stub file was generated by pyright.
"""

import wx
from . import editwindow, frame

"""Crust combines the shell and filling into one control."""
__author__ = ...
class Crust(wx.SplitterWindow):
    """Crust based on SplitterWindow."""
    name = ...
    sashoffset = ...
    def __init__(self, parent, id=..., pos=..., size=..., style=..., name=..., rootObject=..., rootLabel=..., rootIsNamespace=..., intro=..., locals=..., InterpClass=..., startupScript=..., execStartupScript=..., *args, **kwds) -> None:
        """Create Crust instance."""
        ...
    
    def ToggleTools(self): # -> None:
        """Toggle the display of the filling and other tools"""
        ...
    
    def ToolsShown(self): # -> bool:
        ...
    
    def OnChanged(self, event): # -> None:
        """update sash offset from the bottom of the window"""
        ...
    
    def OnSashDClick(self, event): # -> None:
        ...
    
    def SplitterOnSize(self, event): # -> None:
        ...
    
    def LoadSettings(self, config): # -> None:
        ...
    
    def SaveSettings(self, config): # -> None:
        ...
    


class Display(editwindow.EditWindow):
    """STC used to display an object using Pretty Print."""
    def __init__(self, parent, id=..., pos=..., size=..., style=..., static=...) -> None:
        """Create Display instance."""
        ...
    
    def push(self, command, more): # -> None:
        """Receiver for Interpreter.push signal."""
        ...
    
    def Refresh(self): # -> None:
        ...
    
    def setItem(self, item): # -> None:
        """Set item to pretty print in the notebook Display tab."""
        ...
    


class Calltip(wx.TextCtrl):
    """Text control containing the most recent shell calltip."""
    def __init__(self, parent=..., id=..., ShellClassName=...) -> None:
        ...
    
    def display(self, calltip): # -> None:
        """Receiver for this.calltip signal."""
        ...
    


class SessionListing(wx.TextCtrl):
    """Text control containing all commands for session."""
    def __init__(self, parent=..., id=..., ShellClassName=...) -> None:
        ...
    
    def loadHistory(self, history): # -> None:
        ...
    
    def addHistory(self, command): # -> None:
        ...
    
    def clearHistory(self): # -> None:
        ...
    


class DispatcherListing(wx.TextCtrl):
    """Text control containing all dispatches for session."""
    def __init__(self, parent=..., id=...) -> None:
        ...
    
    def spy(self, signal, sender): # -> None:
        """Receiver for Any signal from Any sender."""
        ...
    


class CrustFrame(frame.Frame, frame.ShellFrameMixin):
    """Frame containing all the PyCrust components."""
    name = ...
    def __init__(self, parent=..., id=..., title=..., pos=..., size=..., style=..., rootObject=..., rootLabel=..., rootIsNamespace=..., locals=..., InterpClass=..., config=..., dataDir=..., *args, **kwds) -> None:
        """Create CrustFrame instance."""
        ...
    
    def OnClose(self, event): # -> None:
        """Event handler for closing."""
        ...
    
    def OnAbout(self, event): # -> None:
        """Display an About window."""
        ...
    
    def ToggleTools(self): # -> None:
        """Toggle the display of the filling and other tools"""
        ...
    
    def ToolsShown(self): # -> bool:
        ...
    
    def OnHelp(self, event): # -> None:
        """Show a help dialog."""
        ...
    
    def LoadSettings(self): # -> None:
        ...
    
    def SaveSettings(self, force=...): # -> None:
        ...
    
    def DoSaveSettings(self): # -> None:
        ...
    


