"""
This type stub file was generated by pyright.
"""

"""Document class."""
__author__ = ...
class Document:
    """Document class."""
    def __init__(self, filename=...) -> None:
        """Create a Document instance."""
        ...
    
    def read(self): # -> str:
        """Return contents of file."""
        ...
    
    def write(self, text): # -> None:
        """Write text to file."""
        ...
    


