"""
This type stub file was generated by pyright.
"""

import wx
from wx import stc

"""EditWindow class."""
__author__ = ...
if 'wxMSW' in wx.PlatformInfo:
    FACES = ...
else:
    FACES = ...
class EditWindow(stc.StyledTextCtrl):
    """EditWindow based on StyledTextCtrl."""
    def __init__(self, parent, id=..., pos=..., size=..., style=...) -> None:
        """Create EditWindow instance."""
        ...
    
    def setDisplayLineNumbers(self, state): # -> None:
        ...
    
    def setStyles(self, faces): # -> None:
        """Configure font size, typeface and color for lexer."""
        ...
    
    def OnUpdateUI(self, event): # -> None:
        """Check for matching braces."""
        ...
    
    def CanCopy(self):
        """Return True if text is selected and can be copied."""
        ...
    
    def CanCut(self): # -> bool:
        """Return True if text is selected and can be cut."""
        ...
    
    def CanEdit(self): # -> bool:
        """Return True if editing should succeed."""
        ...
    
    def CanPaste(self): # -> bool:
        """Return True if pasting should succeed."""
        ...
    
    def GetLastPosition(self):
        ...
    
    def GetRange(self, start, end):
        ...
    
    def GetSelection(self): # -> tuple[Any, Any]:
        ...
    
    def ShowPosition(self, pos): # -> None:
        ...
    
    def DoFindNext(self, findData, findDlg=...): # -> None:
        ...
    
    def SetSelection(self, from_, to_): # -> None:
        """Selects the text starting at the first position up to
        (but not including) the character at the last position.
        """
        ...
    


