"""
This type stub file was generated by pyright.
"""

"""Support for icons."""
__author__ = ...
def getPyIcon(shellName=...): # -> Icon:
    ...

def getPyBitmap(shellName=...): # -> Bitmap:
    ...

def getPyImage(shellName=...): # -> Image:
    ...

def getPyData(shellName=...): # -> bytes | None:
    ...

