"""
This type stub file was generated by pyright.
"""

"""magic.py is a utility that allows a simple line from the interpreter
be translated from a more bash-like form to a python form.
For instance, 'plot a' is transformed to 'plot(a)'
Special exceptions are made for predefined ls,cd, and pwd functions"""
__author__ = ...
aliasDict = ...
def magicSingle(command): # -> Literal['', 'ls()', 'pwd()']:
    ...

def magic(command): # -> LiteralString:
    ...

