"""
This type stub file was generated by pyright.
"""

"""parse.py is a utility that allows simple checking for line continuations
to give the shell information about where text is commented and where it is
not and also how to appropriately break up a sequence of commands into
separate multi-line commands...
"""
__author__ = ...
def testForContinuations(codeBlock, ignoreErrors=...):
    ...

