"""
This type stub file was generated by pyright.
"""

"""path.py is a utility containing some very simple path utilities for Py to use"""
__author__ = ...
def pwd(): # -> None:
    ...

def cd(path, usePrint=...): # -> None:
    ...

def ls(str=..., fullpath=...): # -> None:
    ...

def sx(str=...): # -> None:
    ...

