"""
This type stub file was generated by pyright.
"""

"""Provides a variety of classes to create pseudo keywords and pseudo files."""
__author__ = ...
class PseudoKeyword:
    """A callable class that calls a method passed as a parameter.

    Good for creating a pseudo keyword in the python runtime
    environment. The keyword is really an object that has a repr()
    that calls itself which calls the method that was passed in the
    init of the object. All this just to avoid having to type in the
    closing parens on a method. So, for example:

        >>> quit = PseudoKeyword(SomeObject.someMethod)
        >>> quit

    SomeObject.someMethod gets executed as if it had been called
    directly and the user didn't have to type the parens, like
    'quit()'. This technique is most applicable for pseudo keywords
    like quit, exit and help.

    If SomeObject.someMethod can take parameters, they can still be
    passed by using the keyword in the traditional way with parens."""
    def __init__(self, method) -> None:
        """Create a callable object that executes method when called."""
        ...
    
    def __call__(self, *args, **kwds): # -> None:
        ...
    
    def __repr__(self): # -> Literal['']:
        ...
    


class PseudoFile:
    def __init__(self) -> None:
        """Create a file-like object."""
        ...
    
    def readline(self): # -> None:
        ...
    
    def write(self, s): # -> None:
        ...
    
    def writelines(self, l): # -> None:
        ...
    
    def flush(self): # -> None:
        ...
    
    def isatty(self): # -> None:
        ...
    


class PseudoFileIn(PseudoFile):
    def __init__(self, readline, readlines=...) -> None:
        ...
    
    def isatty(self): # -> Literal[1]:
        ...
    


class PseudoFileOut(PseudoFile):
    def __init__(self, write) -> None:
        ...
    
    def isatty(self): # -> Literal[1]:
        ...
    


class PseudoFileErr(PseudoFile):
    def __init__(self, write) -> None:
        ...
    
    def isatty(self): # -> Literal[1]:
        ...
    


