"""
This type stub file was generated by pyright.
"""

"""Provides an object representing the current 'version' or 'release'
of Py as a whole.  Individual classes, such as the shell, filling and
interpreter, each have a revision property based on the CVS Revision."""
__author__ = ...
VERSION = ...
