#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Sun Mar  2 15:17:59 2025
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LocationDownloadDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LocationDownloadDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE | wx.RESIZE_BORDER
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle(_("Dataset Download"))

        self.sizer = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self, wx.ID_ANY, _("Select sample project to download:"), style=wx.ALIGN_LEFT)
        self.sizer.Add(label_1, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.choice = wx.Choice(self, wx.ID_ANY, choices=[_("choice 1")])
        self.choice.SetSelection(0)
        self.sizer.Add(self.choice, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 10)

        self.sizer.Add((0, 10), 0, wx.ALL | wx.EXPAND, 0)

        self.message = wx.TextCtrl(self, wx.ID_ANY, _("Download in progress, wait until it is finished"), style=wx.BORDER_NONE | wx.TE_AUTO_URL | wx.TE_MULTILINE | wx.TE_NOHIDESEL | wx.TE_READONLY | wx.TE_RICH2)
        self.message.SetMinSize(wx.DLG_UNIT(self.message, wx.Size(200, 36)))
        self.message.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_MENUBAR))
        self.message.SetForegroundColour(wx.Colour(255, 0, 0))
        self.sizer.Add(self.message, 1, wx.ALL | wx.EXPAND, 5)

        button_sizer = wx.StdDialogButtonSizer()
        self.sizer.Add(button_sizer, 0, wx.ALIGN_RIGHT | wx.ALL, 10)

        self.cancel_button = wx.Button(self, wx.ID_CANCEL, "")
        button_sizer.AddButton(self.cancel_button)

        self.download_button = wx.Button(self, wx.ID_ANY, _("Do&wnload"))
        self.download_button.SetToolTip(_("Download selected dataset"))
        button_sizer.Add(self.download_button, 0, wx.ALL, 0)

        button_sizer.Realize()

        self.SetSizer(self.sizer)
        self.sizer.Fit(self)
        self.sizer.SetSizeHints(self)

        self.SetAffirmativeId(self.download_button.GetId())
        self.SetEscapeId(self.cancel_button.GetId())

        self.Layout()

        self.choice.Bind(wx.EVT_CHOICE, self.OnChangedChoice)
        self.download_button.Bind(wx.EVT_BUTTON, self.OnDownload)
        # end wxGlade

    def OnChangedChoice(self, event):  # wxGlade: LocationDownloadDialog.<event_handler>
        print("Event handler 'OnChangedChoice' not implemented!")
        event.Skip()

    def OnDownload(self, event):  # wxGlade: LocationDownloadDialog.<event_handler>
        string = "Download completed. The downloaded <https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.tar.gz> sample data is available now in the data tree"
        wx.CallAfter(self.message.SetLabel, string)
        # self.message.SetLabel()

# end of class LocationDownloadDialog

if __name__ == "__main__":
    gettext.install("app1") # replace with the appropriate catalog name

    app1 = wx.App()
    if wx.Platform == '__WXMSW__':
        import ctypes
        ctypes.windll.shcore.SetProcessDpiAwareness(2)
    dialog_1 = LocationDownloadDialog(None, wx.ID_ANY, "")
    app1.SetTopWindow(dialog_1)
    dialog_1.ShowModal()
    dialog_1.Destroy()
    app1.MainLoop()
