[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
(
    # exclude directories in the root of the project
    /(
          \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | bin\..*
        | dist\..*
    )/
    | python/libgrass_interface_generator/
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
python_files = "*/tests/*_test.py"
addopts = """
    --ignore-glob='dist.*'
    --ignore-glob='bin.*'
    --ignore-glob='*/tests/data/*'
    --ignore-glob='*/grass/pygrass/tests/*'
    --doctest-glob='*doctest*.txt'
    --ignore='raster/r.category/test_rcategory_doctest.txt'
"""
timeout = 300

[tool.ruff]
# builtins = ["_"]
# exclude = ["python/libgrass_interface_generator/"]
extend-include = ["*.ipynb"]
# [tool.ruff]
builtins = ["_"]
exclude = [
    # ".git",
    # "__pycache__",
    # ".env",
    # ".venv",
    # "env",
    # "venv",
    # "ENV",
    # "env.bak",
    # "venv.bak",
    # "bin.*",
    # "dist.*",
    # "OBJ.*",
    # "testreport",
    "python/libgrass_interface_generator",
    "testsuite",
]
ignore = []
line-length = 88
select = [
    "E",
    "F",
    "W",
]

[tool.ruff.per-file-ignores]
"utils/g.html2man/ggroff.py" = ["W605"]
"gui/wxpython/photo2image/*" = [
    "F841",
    "E722",
    "E501",
]
"python/grass/temporal/temporal_algebra.py" = [
    "E741",
    "E501",
    "F841",
    "E722",
]
"python/grass/temporal/temporal_raster3d_algebra.py" = ["E741"]
"gui/wxpython/location_wizard/dialogs.py" = [
    "F841",
    "E501",
]
"gui/wxpython/rlisetup/frame.py" = ["E741"]
"scripts/r.in.wms/srs.py" = [
    "E722",
    "E501",
]
"scripts/d.rast.edit/d.rast.edit.py" = [
    "E722",
    "E501",
]
"python/grass/temporal/abstract_space_time_dataset.py" = [
    "W605",
    "E501",
    "F841",
    "E722",
]
"gui/wxpython/rdigit/g.gui.rdigit.py" = ["F841"]
"gui/wxpython/lmgr/giface.py" = [
    "E501",
    "E741",
]
"gui/wxpython/tplot/frame.py" = [
    "F841",
    "E722",
]
"python/grass/pygrass/tests/benchmark.py" = [
    "E501",
    "E402",
    "F401",
    "F821",
]
"man/parser_standard_options.py" = [
    "F403",
    "F405",
]
"python/grass/docs/conf.py" = [
    "E402",
    "E501",
]
"scripts/r.fillnulls/r.fillnulls.py" = [
    "E722",
    "E501",
]
"scripts/i.in.spotvgt/i.in.spotvgt.py" = ["E501"]
"gui/wxpython/core/render.py" = [
    "E722",
    "F841",
    "E501",
]
"python/grass/pygrass/vector/geometry.py" = ["W605"]
"python/grass/temporal/core.py" = [
    "E501",
    "E722",
]
"python/grass/temporal/temporal_granularity.py" = [
    "E501",
    "F841",
    "E722",
]
"python/grass/temporal/temporal_vector_algebra.py" = [
    "E741",
    "E501",
    "F841",
]
"gui/wxpython/core/toolboxes.py" = [
    "E722",
    "E501",
]
"gui/scripts/d.rast3d.py" = ["E501"]
"gui/wxpython/gui_core/treeview.py" = [
    "E501",
    "F841",
]
"scripts/r.in.wms/wms_drv.py" = [
    "E402",
    "E722",
    "E501",
]
"gui/wxpython/lmgr/layertree.py" = [
    "E722",
    "E501",
]
"gui/wxpython/mapwin/base.py" = [
    "E722",
    "E501",
]
"python/grass/script/vector.py" = ["E501"]
"python/grass/script/task.py" = ["W605"]
"scripts/i.pansharpen/i.pansharpen.py" = [
    "E722",
    "E501",
]
"imagery/i.atcorr/create_iwave.py" = [
    "E501",
    "F632",
    "F821",
]
"gui/wxpython/iclass/statistics.py" = [
    "F841",
    "F405",
    "F403",
]
"gui/wxpython/tools/build_modules_xml.py" = [
    "E722",
    "E501",
]
"gui/wxpython/animation/g.gui.animation.py" = ["E501"]
"utils/mkrest.py" = [
    "E501",
    "W605",
]
"gui/wxpython/gcp/manager.py" = [
    "E501",
    "F841",
    "E722",
]
"gui/wxpython/gui_core/*" = [
    "F841",
    "E722",
    "W605",
]
"gui/wxpython/gui_core/preferences.py" = [
    "E501",
    "F841",
]
"gui/wxpython/gui_core/widgets.py" = [
    "E501",
    "F841",
    "E722",
]
"gui/wxpython/iclass/digit.py" = [
    "F405",
    "F403",
]
"python/grass/pygrass/raster/rowio.py" = ["E741"]
"python/grass/pygrass/modules/interface/parameter.py" = [
    "E501",
    "W605",
]
"gui/wxpython/mapswipe/g.gui.mapswipe.py" = ["E501"]
"python/grass/temporal/datetime_math.py" = [
    "E501",
    "F841",
    "E722",
]
"gui/wxpython/gui_core/ghelp.py" = [
    "E501",
    "E722",
]
"scripts/r.in.wms/wms_cap_parsers.py" = [
    "F841",
    "E741",
    "E501",
]
"python/grass/*/__init__.py" = [
    "F401",
    "F403",
]
"scripts/v.report/v.report.py" = [
    "F841",
    "E501",
]
"scripts/*/*.py" = ["E501"]
"gui/wxpython/web_services/dialogs.py" = ["E501"]
"man/build_check.py" = [
    "F403",
    "F405",
]
"man/build_keywords.py" = [
    "F403",
    "F405",
    "E722",
]
"gui/wxpython/nviz/*" = [
    "F841",
    "E722",
    "W605",
    "F403",
    "F405",
    "E501",
]
"python/grass/pygrass/modules/interface/*.py" = [
    "E501",
    "F401",
]
"python/grass/pygrass/raster/*.py" = ["E501"]
"gui/wxpython/mapwin/graphics.py" = ["E722"]
"gui/wxpython/dbmgr/base.py" = [
    "E501",
    "E722",
    "F841",
]
"gui/wxpython/vnet/*" = [
    "F841",
    "E501",
]
"gui/wxpython/wxplot/base.py" = [
    "F841",
    "E722",
]
"gui/wxpython/gui_core/forms.py" = [
    "E501",
    "E722",
    "F841",
]
"gui/wxpython/startup/locdownload.py" = [
    "E722",
    "E402",
    "E501",
]
"scripts/g.extension/g.extension.py" = [
    "F841",
    "E722",
    "E501",
]
"lib/init/grass.py" = [
    "E501",
    "E722",
    "F821",
    "F841",
    "W605",
]
"python/grass/temporal/aggregation.py" = ["E501"]
"python/grass/temporal/temporal_topology_dataset_connector.py" = [
    "E501",
    "E722",
]
"scripts/d.rast.leg/d.rast.leg.py" = ["E741"]
"gui/wxpython/rlisetup/wizard.py" = [
    "E722",
    "E741",
]
"gui/wxpython/wxplot/profile.py" = [
    "F841",
    "E722",
]
"gui/wxpython/core/gcmd.py" = [
    "E402",
    "E501",
]
"gui/wxpython/core/giface.py" = ["E501"]
"gui/wxpython/docs/wxgui_sphinx/conf.py" = [
    "E402",
    "E501",
]
"python/grass/*/*/*/__init__.py" = [
    "F401",
    "F403",
]
"gui/scripts/d.wms.py" = ["E501"]
"gui/wxpython/wxplot/histogram.py" = ["E722"]
"python/grass/pygrass/vector/table.py" = ["E501"]
"python/grass/pygrass/rpc/__init__.py" = [
    "E501",
    "F401",
    "F403",
]
"gui/wxpython/mapdisp/frame.py" = ["E501"]
"doc/gui/wxpython/example/g.gui.example.py" = ["E501"]
"doc/gui/wxpython/example/dialogs.py" = ["F401"]
"gui/wxpython/core/ws.py" = [
    "F841",
    "E501",
]
"gui/wxpython/web_services/widgets.py" = [
    "F841",
    "E741",
    "W605",
    "E402",
    "E501",
]
"python/grass/temporal/temporal_raster_base_algebra.py" = [
    "E501",
    "F841",
    "E722",
]
"gui/wxpython/image2target/*" = [
    "F841",
    "E722",
    "E501",
]
"doc/python/vector_example_ctypes.py" = [
    "F403",
    "F405",
]
"scripts/v.what.strds/v.what.strds.py" = [
    "E722",
    "E501",
]
"gui/wxpython/location_wizard/wizard.py" = ["E722"]
"python/grass/gunittest/gmodules.py" = [
    "E501",
    "W605",
]
"gui/wxpython/iclass/g.gui.iclass.py" = ["E501"]
"gui/wxpython/iclass/frame.py" = [
    "F405",
    "F403",
    "E501",
]
"gui/wxpython/menustrings.py" = ["E501"]
"gui/wxpython/mapdisp/test_mapdisp.py" = ["E501"]
"gui/wxpython/core/gconsole.py" = [
    "E722",
    "W605",
]
"locale/grass_po_stats.py" = [
    "E401",
    "E501",
    "E722",
    "E741",
]
"gui/wxpython/wxplot/dialogs.py" = ["E501"]
"python/grass/pydispatch/saferef.py" = ["F821"]
"python/grass/temporal/space_time_datasets.py" = ["E501"]
"scripts/r.semantic.label/r.semantic.label.py" = [
    "F841",
    "E501",
]
"gui/wxpython/web_services/cap_interface.py" = ["E501"]
"python/grass/temporal/list_stds.py" = ["E501"]
"python/grass/temporal/base.py" = ["E501"]
"scripts/d.frame/d.frame.py" = [
    "E722",
    "E501",
]
"python/grass/temporal/spatio_temporal_relationships.py" = ["E501"]
"scripts/v.unpack/v.unpack.py" = [
    "F841",
    "E722",
    "E501",
]
"gui/wxpython/wxplot/scatter.py" = ["E501"]
"gui/wxpython/tplot/g.gui.tplot.py" = ["E501"]
"gui/wxpython/iclass/dialogs.py" = [
    "E741",
    "E501",
]
"man/build_class.py" = [
    "F403",
    "F405",
]
"gui/wxpython/core/utils.py" = [
    "E722",
    "F841",
    "W605",
]
"gui/wxpython/modules/*" = [
    "F841",
    "E722",
    "W605",
    "E501",
]
"scripts/db.univar/db.univar.py" = [
    "E741",
    "E501",
]
"temporal/*/*.py" = ["E501"]
"python/grass/temporal/temporal_extent.py" = ["E501"]
"gui/wxpython/mapwin/buffered.py" = [
    "E722",
    "E501",
]
"gui/wxpython/wxgui.py" = ["F841"]
"python/grass/temporal/spatial_topology_dataset_connector.py" = [
    "E501",
    "E722",
]
"python/grass/temporal/metadata.py" = ["E501"]
"python/grass/pygrass/modules/interface/module.py" = [
    "E501",
    "W605",
]
"scripts/db.out.ogr/db.out.ogr.py" = ["F841"]
"gui/wxpython/gcp/mapdisplay.py" = ["F841"]
"scripts/d.polar/d.polar.py" = [
    "F841",
    "E501",
]
"gui/wxpython/dbmgr/manager.py" = [
    "E501",
    "E722",
]
"gui/wxpython/gui_core/dialogs.py" = [
    "E501",
    "E722",
    "F841",
    "W605",
]
"gui/wxpython/psmap/*" = [
    "F841",
    "E722",
    "F405",
    "F403",
    "E501",
]
"gui/wxpython/mapdisp/main.py" = [
    "E722",
    "E501",
]
"gui/wxpython/core/debug.py" = ["E501"]
"man/build_full_index_rest.py" = [
    "F403",
    "F405",
]
"gui/wxpython/dbmgr/sqlbuilder.py" = [
    "E501",
    "E722",
    "F841",
]
"python/grass/temporal/temporal_raster_algebra.py" = ["E741"]
"python/grass/temporal/open_stds.py" = ["F841"]
"gui/wxpython/mapdisp/toolbars.py" = ["E501"]
"python/grass/script/db.py" = ["E501"]
"gui/wxpython/dbmgr/vinfo.py" = ["F841"]
"gui/wxpython/gmodeler/*" = [
    "F841",
    "E722",
    "W605",
    "F405",
    "F403",
    "E402",
]
"gui/wxpython/lmgr/frame.py" = [
    "F841",
    "E722",
    "W605",
    "E501",
]
"gui/wxpython/rdigit/toolbars.py" = ["E501"]
"gui/wxpython/timeline/g.gui.timeline.py" = ["E501"]
"man/build_index_rest.py" = [
    "F403",
    "F405",
]
"gui/wxpython/gui_core/gselect.py" = [
    "E501",
    "F841",
    "E722",
]
"gui/wxpython/mapwin/decorations.py" = ["E501"]
"gui/wxpython/core/gthread.py" = ["F841"]
"python/grass/pygrass/utils.py" = [
    "E402",
    "E501",
]
"man/build_rest.py" = ["E501"]
"gui/wxpython/core/settings.py" = ["E722"]
"python/grass/pygrass/modules/grid/*.py" = [
    "E501",
    "F401",
]
"python/grass/*/*/__init__.py" = [
    "F401",
    "F403",
]
"python/grass/temporal/univar_statistics.py" = ["E501"]
"man/build_html.py" = ["E501"]
"gui/wxpython/core/globalvar.py" = ["W605"]
"python/grass/imaging/images2gif.py" = ["E501"]
"gui/wxpython/core/watchdog.py" = ["E402"]
"doc/python/m.distance.py" = [
    "F403",
    "F405",
    "E501",
]
"gui/wxpython/vdigit/*" = [
    "F841",
    "E722",
    "E741",
    "F405",
    "F403",
    "E501",
]
"gui/wxpython/animation/temporal_manager.py" = ["E501"]
"python/grass/temporal/abstract_map_dataset.py" = ["E501"]
"scripts/v.import/v.import.py" = [
    "F841",
    "E722",
    "E501",
]
"temporal/t.rast.what/t.rast.what.py" = [
    "F841",
    "E501",
]
"temporal/t.rast.to.vect/t.rast.to.vect.py" = [
    "F841",
    "E501",
]
"python/grass/temporal/temporal_operator.py" = ["E501"]
"scripts/r.in.srtm/r.in.srtm.py" = [
    "E722",
    "E501",
]
"man/build_class_rest.py" = [
    "F403",
    "F405",
]
"python/grass/gunittest/*.py" = ["E501"]
"utils/gitlog2changelog.py" = [
    "E722",
    "E712",
    "W605",
]
"gui/wxpython/iscatt/*" = [
    "F841",
    "E722",
    "E741",
    "F405",
    "F403",
    "E501",
]
"gui/wxpython/lmgr/workspace.py" = ["F841"]
"gui/wxpython/animation/provider.py" = [
    "F841",
    "E501",
]
"man/build_check_rest.py" = [
    "F403",
    "F405",
]
"python/grass/temporal/register.py" = ["E501"]
"gui/wxpython/dbmgr/dialogs.py" = [
    "E501",
    "F841",
    "E722",
]
"gui/wxpython/mapdisp/statusbar.py" = [
    "F841",
    "E501",
]
"scripts/r.in.wms/wms_gdal_drv.py" = [
    "F841",
    "E722",
    "E501",
]
"temporal/t.vect.algebra/t.vect.algebra.py" = [
    "F841",
    "E501",
]
"python/grass/temporal/spatial_extent.py" = ["E501"]
"python/grass/pygrass/vector/__init__.py" = [
    "E402",
    "E501",
    "E402",
]
"man/build_topics.py" = [
    "F403",
    "F405",
    "E722",
]
"gui/wxpython/animation/mapwindow.py" = ["F841"]
"gui/wxpython/datacatalog/tree.py" = [
    "E731",
    "E402",
    "E501",
]
"python/grass/temporal/c_libraries_interface.py" = [
    "E501",
    "F841",
    "E722",
]
"doc/python/raster_example_ctypes.py" = [
    "F403",
    "F405",
]
"gui/wxpython/core/workspace.py" = [
    "E722",
    "E501",
]
"python/grass/pygrass/raster/__init__.py" = ["E402"]
"man/build_index.py" = [
    "F403",
    "F405",
]
"scripts/r.unpack/r.unpack.py" = ["E501"]
"gui/wxpython/gcp/g.gui.gcp.py" = ["F841"]
"gui/wxpython/rlisetup/sampling_frame.py" = ["F841"]
"man/build_full_index.py" = [
    "F403",
    "F405",
]