[tool.black]
line-length = 88
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
exclude = '''
(
    # exclude directories in the root of the project
    /(
          \.eggs
        | \.git
        | \.hg
        | \.mypy_cache
        | \.tox
        | \.venv
        | _build
        | buck-out
        | build
        | bin\..*
        | dist\..*
    )/
    | python/libgrass_interface_generator/
)
'''

[tool.pytest.ini_options]
minversion = "6.0"
#python_files = "*/tests/*_test.py"
addopts = """
    --ignore-glob='*/testsuite/*'
    --ignore-glob='dist.*'
    --ignore-glob='bin.*'
    --ignore-glob='*/tests/data/*'
    --ignore-glob='*/grass/pygrass/tests/*'
    --doctest-glob='*doctest*.txt'
    --ignore='docker/testdata/test_grass_python.py'
    --ignore='docker/testdata/test_grass_session.py'
    --ignore='gui/wxpython/mapdisp/test_mapdisp.py'
    --ignore='raster/r.category/test_rcategory_doctest.txt'
    --ignore='utils/test_generate_last_commit_file.py'
"""
timeout = 300
