---
name: Setup OSGeo4W environment
description: Install OSGeo4W and OSGeo4W packages on Windows
author: "Edouard Choinière"

inputs:
  packages:
    description: List of OSGeo4W packages to install
    required: false
  root:
    description: Root installation directory, by default C:\OSGeo4W.
    required: false
    default: C:\OSGeo4W
  package-dir:
    description: Location where to download packages. Using a folder in a faster drive, like D:\OSGeo4W_pkg, reduces installation time.
    required: false
  site:
    description: Download site URL to use
    required: false
    default: "http://download.osgeo.org/osgeo4w/v2/"
  upgrade-also:
    description: Also upgrade installed packages
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: "Download OSGeo4W installer"
      id: download
      shell: pwsh
      run: |
        "::group::Download OSGeo4W installer"
        $exe = 'osgeo4w-setup.exe'
        $url = '${{ inputs.site }}' + $exe
        $setup = '.\' + $exe
        echo "Starting download of $url..."
        echo "setup_path=$setup" >> "$env:GITHUB_OUTPUT"
        Invoke-WebRequest $url -OutFile $setup
        echo "Download completed"
        "::endgroup::"
    - name: Ensure package dir exists
      if: ${{ inputs.package-dir }}
      shell: pwsh
      run: |
       echo "::group::Ensure package dir exists"
       mkdir -Force '${{ inputs.package-dir }}'
       echo "::endgroup::"
    - name: Run setup
      run: |
        "::group::Run setup"
        $setup = '${{ steps.download.outputs.setup_path }}'
        echo "Setup executable is $setup"
        $args = @(
            '--advanced', # Advanced install (default)'
            '-k',
            '--quiet-mode', # Unattended setup mode
            '-s', 'http://download.osgeo.org/osgeo4w/v2/'
            # '-P', '${{ env.Deps }}',
            # '--local-package-dir', $pkg_dir,
            # '--root', '${{ env.OSGEO4W_ROOT }}'
          )
        if ('${{ inputs.upgrade-also }}' -eq $true) {
          $args += '--upgrade-also'
        }
        & $setup $args | Out-Default
        echo "::endgroup::"
      shell: powershell
