"""
This type stub file was generated by pyright.
"""

import wx

"""
`wx.aui` provides a set of classes for implementing an "Advanced User Interface".
More specifically, these classes enable to you present some of your application in
floating or dockable panels, notebooks with floatable tabs, etc.

There is also a pure-python implementation of these classes available in the
`wx.lib.agw.aui` package.
"""
AUI_DOCK_NONE = ...
AUI_DOCK_TOP = ...
AUI_DOCK_RIGHT = ...
AUI_DOCK_BOTTOM = ...
AUI_DOCK_LEFT = ...
AUI_DOCK_CENTER = ...
AUI_DOCK_CENTRE = ...
AUI_MGR_ALLOW_FLOATING = ...
AUI_MGR_ALLOW_ACTIVE_PANE = ...
AUI_MGR_TRANSPARENT_DRAG = ...
AUI_MGR_TRANSPARENT_HINT = ...
AUI_MGR_VENETIAN_BLINDS_HINT = ...
AUI_MGR_RECTANGLE_HINT = ...
AUI_MGR_HINT_FADE = ...
AUI_MGR_NO_VENETIAN_BLINDS_FADE = ...
AUI_MGR_LIVE_RESIZE = ...
AUI_MGR_DEFAULT = ...
wxEVT_AUI_PANE_BUTTON = ...
wxEVT_AUI_PANE_CLOSE = ...
wxEVT_AUI_PANE_MAXIMIZE = ...
wxEVT_AUI_PANE_RESTORE = ...
wxEVT_AUI_PANE_ACTIVATED = ...
wxEVT_AUI_RENDER = ...
wxEVT_AUI_FIND_MANAGER = ...
class AuiManager(wx.EvtHandler):
    """
    AuiManager(managed_wnd=None, flags=AUI_MGR_DEFAULT)
    
    wxAuiManager is the central class of the wxAUI class framework.
    """
    def __init__(self, managed_wnd=..., flags=...) -> None:
        """
        AuiManager(managed_wnd=None, flags=AUI_MGR_DEFAULT)
        
        wxAuiManager is the central class of the wxAUI class framework.
        """
        ...
    
    def AddPane(self, *args, **kw):
        """
        AddPane(window, pane_info) -> bool
        AddPane(window, direction=wx.LEFT, caption=wx.EmptyString) -> bool
        AddPane(window, pane_info, drop_pos) -> bool
        
        AddPane() tells the frame manager to start managing a child window.
        """
        ...
    
    def GetPane(self, *args, **kw):
        """
        GetPane(window) -> AuiPaneInfo
        GetPane(name) -> AuiPaneInfo
        
        GetPane() is used to lookup a wxAuiPaneInfo object either by window
        pointer or by pane name, which acts as a unique id for a window pane.
        """
        ...
    
    def CalculateHintRect(self, paneWindow, pt, offset):
        """
        CalculateHintRect(paneWindow, pt, offset) -> wx.Rect
        
        This function is used by controls to calculate the drop hint
        rectangle.
        """
        ...
    
    def CanDockPanel(self, p):
        """
        CanDockPanel(p) -> bool
        
        Check if a key modifier is pressed (actually WXK_CONTROL or WXK_ALT)
        while dragging the frame to not dock the window.
        """
        ...
    
    def ClosePane(self, paneInfo):
        """
        ClosePane(paneInfo)
        
        Destroys or hides the given pane depending on its flags.
        """
        ...
    
    def CreateFloatingFrame(self, parent, p):
        """
        CreateFloatingFrame(parent, p) -> AuiFloatingFrame
        
        Creates a floating frame in this wxAuiManager with the given parent
        and wxAuiPaneInfo.
        """
        ...
    
    def DetachPane(self, window):
        """
        DetachPane(window) -> bool
        
        Tells the wxAuiManager to stop managing the pane specified by window.
        """
        ...
    
    def DrawHintRect(self, paneWindow, pt, offset):
        """
        DrawHintRect(paneWindow, pt, offset)
        
        This function is used by controls to draw the hint window.
        """
        ...
    
    def GetAllPanes(self):
        """
        GetAllPanes() -> AuiPaneInfoArray
        
        Returns an array of all panes managed by the frame manager.
        """
        ...
    
    def GetArtProvider(self):
        """
        GetArtProvider() -> AuiDockArt
        
        Returns the current art provider being used.
        """
        ...
    
    def GetDockSizeConstraint(self, widthpct, heightpct):
        """
        GetDockSizeConstraint(widthpct, heightpct)
        
        Returns the current dock constraint values.
        """
        ...
    
    def GetFlags(self):
        """
        GetFlags() -> unsignedint
        
        Returns the current wxAuiManagerOption's flags.
        """
        ...
    
    def GetManagedWindow(self):
        """
        GetManagedWindow() -> wx.Window
        
        Returns the frame currently being managed by wxAuiManager.
        """
        ...
    
    def HasLiveResize(self):
        """
        HasLiveResize() -> bool
        
        Returns true if windows are resized live.
        """
        ...
    
    def HideHint(self):
        """
        HideHint()
        
        HideHint() hides any docking hint that may be visible.
        """
        ...
    
    def InsertPane(self, window, insert_location, insert_level=...):
        """
        InsertPane(window, insert_location, insert_level=AUI_INSERT_PANE) -> bool
        
        This method is used to insert either a previously unmanaged pane
        window into the frame manager, or to insert a currently managed pane
        somewhere else.
        """
        ...
    
    def LoadPaneInfo(self, pane_part, pane):
        """
        LoadPaneInfo(pane_part, pane)
        
        LoadPaneInfo() is similar to LoadPerspective, with the exception that
        it only loads information about a single pane.
        """
        ...
    
    def LoadPerspective(self, perspective, update=...):
        """
        LoadPerspective(perspective, update=True) -> bool
        
        Loads a saved perspective.
        """
        ...
    
    def MaximizePane(self, paneInfo):
        """
        MaximizePane(paneInfo)
        
        Maximize the given pane.
        """
        ...
    
    def RestorePane(self, paneInfo):
        """
        RestorePane(paneInfo)
        
        Restore the last state of the given pane.
        """
        ...
    
    def RestoreMaximizedPane(self):
        """
        RestoreMaximizedPane()
        
        Restore the previously maximized pane.
        """
        ...
    
    def SavePaneInfo(self, pane):
        """
        SavePaneInfo(pane) -> String
        
        SavePaneInfo() is similar to SavePerspective, with the exception that
        it only saves information about a single pane.
        """
        ...
    
    def SavePerspective(self):
        """
        SavePerspective() -> String
        
        Saves the entire user interface layout into an encoded wxString, which
        can then be stored by the application (probably using wxConfig).
        """
        ...
    
    def SetArtProvider(self, art_provider):
        """
        SetArtProvider(art_provider)
        
        Instructs wxAuiManager to use art provider specified by parameter
        art_provider for all drawing calls.
        """
        ...
    
    def SetDockSizeConstraint(self, widthpct, heightpct):
        """
        SetDockSizeConstraint(widthpct, heightpct)
        
        When a user creates a new dock by dragging a window into a docked
        position, often times the large size of the window will create a dock
        that is unwieldy large.
        """
        ...
    
    def SetFlags(self, flags):
        """
        SetFlags(flags)
        
        This method is used to specify wxAuiManagerOption's flags.
        """
        ...
    
    def SetManagedWindow(self, managed_wnd):
        """
        SetManagedWindow(managed_wnd)
        
        Called to specify the frame or window which is to be managed by
        wxAuiManager.
        """
        ...
    
    def ShowHint(self, rect):
        """
        ShowHint(rect)
        
        This function is used by controls to explicitly show a hint window at
        the specified rectangle.
        """
        ...
    
    def StartPaneDrag(self, paneWindow, offset):
        """
        StartPaneDrag(paneWindow, offset)
        
        Mostly used internally to define the drag action parameters.
        """
        ...
    
    def UnInit(self):
        """
        UnInit()
        
        Dissociate the managed window from the manager.
        """
        ...
    
    def Update(self):
        """
        Update()
        
        This method is called after any number of changes are made to any of
        the managed panes.
        """
        ...
    
    @staticmethod
    def AlwaysUsesLiveResize():
        """
        AlwaysUsesLiveResize() -> bool
        
        Returns true if live resize is always used on the current platform.
        """
        ...
    
    @staticmethod
    def GetManager(window):
        """
        GetManager(window) -> AuiManager
        
        Calling this method will return the wxAuiManager for a given window.
        """
        ...
    
    AllPanes = ...
    ArtProvider = ...
    Flags = ...
    ManagedWindow = ...
    def ProcessDockResult(self, target, new_pos):
        """
        ProcessDockResult(target, new_pos) -> bool
        
        ProcessDockResult() is a protected member of the wxAUI layout manager.
        """
        ...
    


class AuiPaneInfo:
    """
    AuiPaneInfo()
    AuiPaneInfo(c)
    
    wxAuiPaneInfo is part of the wxAUI class framework.
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiPaneInfo()
        AuiPaneInfo(c)
        
        wxAuiPaneInfo is part of the wxAUI class framework.
        """
        ...
    
    def BestSize(self, *args, **kw):
        """
        BestSize(size) -> AuiPaneInfo
        BestSize(x, y) -> AuiPaneInfo
        
        BestSize() sets the ideal size for the pane.
        """
        ...
    
    def Centre(self):
        """
        Centre() -> AuiPaneInfo
        
        Center() sets the pane dock position to the left side of the frame.
        """
        ...
    
    def Center(self):
        """
        Center() -> AuiPaneInfo
        
        Center() sets the pane dock position to the left side of the frame.
        """
        ...
    
    def CentrePane(self):
        """
        CentrePane() -> AuiPaneInfo
        
        CentrePane() specifies that the pane should adopt the default center
        pane settings.
        """
        ...
    
    def CenterPane(self):
        """
        CenterPane() -> AuiPaneInfo
        
        CentrePane() specifies that the pane should adopt the default center
        pane settings.
        """
        ...
    
    def FloatingPosition(self, *args, **kw):
        """
        FloatingPosition(pos) -> AuiPaneInfo
        FloatingPosition(x, y) -> AuiPaneInfo
        
        FloatingPosition() sets the position of the floating pane.
        """
        ...
    
    def FloatingSize(self, *args, **kw):
        """
        FloatingSize(size) -> AuiPaneInfo
        FloatingSize(x, y) -> AuiPaneInfo
        
        FloatingSize() sets the size of the floating pane.
        """
        ...
    
    def MaxSize(self, *args, **kw):
        """
        MaxSize(size) -> AuiPaneInfo
        MaxSize(x, y) -> AuiPaneInfo
        
        MaxSize() sets the maximum size of the pane.
        """
        ...
    
    def MinSize(self, *args, **kw):
        """
        MinSize(size) -> AuiPaneInfo
        MinSize(x, y) -> AuiPaneInfo
        
        MinSize() sets the minimum size of the pane.
        """
        ...
    
    name = ...
    caption = ...
    icon = ...
    window = ...
    frame = ...
    state = ...
    dock_direction = ...
    dock_layer = ...
    dock_row = ...
    dock_pos = ...
    best_size = ...
    min_size = ...
    max_size = ...
    floating_pos = ...
    floating_size = ...
    dock_proportion = ...
    rect = ...
    def Bottom(self):
        """
        Bottom() -> AuiPaneInfo
        
        Bottom() sets the pane dock position to the bottom side of the frame.
        """
        ...
    
    def BottomDockable(self, b=...):
        """
        BottomDockable(b=True) -> AuiPaneInfo
        
        BottomDockable() indicates whether a pane can be docked at the bottom
        of the frame.
        """
        ...
    
    def Caption(self, c):
        """
        Caption(c) -> AuiPaneInfo
        
        Caption() sets the caption of the pane.
        """
        ...
    
    def CaptionVisible(self, visible=...):
        """
        CaptionVisible(visible=True) -> AuiPaneInfo
        
        CaptionVisible indicates that a pane caption should be visible.
        """
        ...
    
    def CloseButton(self, visible=...):
        """
        CloseButton(visible=True) -> AuiPaneInfo
        
        CloseButton() indicates that a close button should be drawn for the
        pane.
        """
        ...
    
    def DefaultPane(self):
        """
        DefaultPane() -> AuiPaneInfo
        
        DefaultPane() specifies that the pane should adopt the default pane
        settings.
        """
        ...
    
    def DestroyOnClose(self, b=...):
        """
        DestroyOnClose(b=True) -> AuiPaneInfo
        
        DestroyOnClose() indicates whether a pane should be destroyed when it
        is closed.
        """
        ...
    
    def Direction(self, direction):
        """
        Direction(direction) -> AuiPaneInfo
        
        Direction() determines the direction of the docked pane.
        """
        ...
    
    def Dock(self):
        """
        Dock() -> AuiPaneInfo
        
        Dock() indicates that a pane should be docked.
        """
        ...
    
    def DockFixed(self, b=...):
        """
        DockFixed(b=True) -> AuiPaneInfo
        
        DockFixed() causes the containing dock to have no resize sash.
        """
        ...
    
    def Dockable(self, b=...):
        """
        Dockable(b=True) -> AuiPaneInfo
        
        Dockable() specifies whether a frame can be docked or not.
        """
        ...
    
    def Fixed(self):
        """
        Fixed() -> AuiPaneInfo
        
        Fixed() forces a pane to be fixed size so that it cannot be resized.
        """
        ...
    
    def Float(self):
        """
        Float() -> AuiPaneInfo
        
        Float() indicates that a pane should be floated.
        """
        ...
    
    def Floatable(self, b=...):
        """
        Floatable(b=True) -> AuiPaneInfo
        
        Floatable() sets whether the user will be able to undock a pane and
        turn it into a floating window.
        """
        ...
    
    def Gripper(self, visible=...):
        """
        Gripper(visible=True) -> AuiPaneInfo
        
        Gripper() indicates that a gripper should be drawn for the pane.
        """
        ...
    
    def GripperTop(self, attop=...):
        """
        GripperTop(attop=True) -> AuiPaneInfo
        
        GripperTop() indicates that a gripper should be drawn at the top of
        the pane.
        """
        ...
    
    def HasBorder(self):
        """
        HasBorder() -> bool
        
        HasBorder() returns true if the pane displays a border.
        """
        ...
    
    def HasCaption(self):
        """
        HasCaption() -> bool
        
        HasCaption() returns true if the pane displays a caption.
        """
        ...
    
    def HasCloseButton(self):
        """
        HasCloseButton() -> bool
        
        HasCloseButton() returns true if the pane displays a button to close
        the pane.
        """
        ...
    
    def HasFlag(self, flag):
        """
        HasFlag(flag) -> bool
        
        HasFlag() returns true if the property specified by flag is active for
        the pane.
        """
        ...
    
    def HasGripper(self):
        """
        HasGripper() -> bool
        
        HasGripper() returns true if the pane displays a gripper.
        """
        ...
    
    def HasGripperTop(self):
        """
        HasGripperTop() -> bool
        
        HasGripper() returns true if the pane displays a gripper at the top.
        """
        ...
    
    def HasMaximizeButton(self):
        """
        HasMaximizeButton() -> bool
        
        HasMaximizeButton() returns true if the pane displays a button to
        maximize the pane.
        """
        ...
    
    def HasMinimizeButton(self):
        """
        HasMinimizeButton() -> bool
        
        HasMinimizeButton() returns true if the pane displays a button to
        minimize the pane.
        """
        ...
    
    def HasPinButton(self):
        """
        HasPinButton() -> bool
        
        HasPinButton() returns true if the pane displays a button to float the
        pane.
        """
        ...
    
    def Hide(self):
        """
        Hide() -> AuiPaneInfo
        
        Hide() indicates that a pane should be hidden.
        """
        ...
    
    def Icon(self, b):
        """
        Icon(b) -> AuiPaneInfo
        
        Icon() sets the icon of the pane.
        """
        ...
    
    def IsBottomDockable(self):
        """
        IsBottomDockable() -> bool
        
        IsBottomDockable() returns true if the pane can be docked at the
        bottom of the managed frame.
        """
        ...
    
    def IsDockable(self):
        """
        IsDockable() -> bool
        
        Returns true if the pane can be docked at any side.
        """
        ...
    
    def IsDocked(self):
        """
        IsDocked() -> bool
        
        IsDocked() returns true if the pane is currently docked.
        """
        ...
    
    def IsFixed(self):
        """
        IsFixed() -> bool
        
        IsFixed() returns true if the pane cannot be resized.
        """
        ...
    
    def IsFloatable(self):
        """
        IsFloatable() -> bool
        
        IsFloatable() returns true if the pane can be undocked and displayed
        as a floating window.
        """
        ...
    
    def IsFloating(self):
        """
        IsFloating() -> bool
        
        IsFloating() returns true if the pane is floating.
        """
        ...
    
    def IsLeftDockable(self):
        """
        IsLeftDockable() -> bool
        
        IsLeftDockable() returns true if the pane can be docked on the left of
        the managed frame.
        """
        ...
    
    def IsMovable(self):
        """
        IsMovable() -> bool
        
        IsMoveable() returns true if the docked frame can be undocked or moved
        to another dock position.
        """
        ...
    
    def IsOk(self):
        """
        IsOk() -> bool
        
        IsOk() returns true if the wxAuiPaneInfo structure is valid.
        """
        ...
    
    def IsResizable(self):
        """
        IsResizable() -> bool
        
        IsResizable() returns true if the pane can be resized.
        """
        ...
    
    def IsRightDockable(self):
        """
        IsRightDockable() -> bool
        
        IsRightDockable() returns true if the pane can be docked on the right
        of the managed frame.
        """
        ...
    
    def IsShown(self):
        """
        IsShown() -> bool
        
        IsShown() returns true if the pane is currently shown.
        """
        ...
    
    def IsToolbar(self):
        """
        IsToolbar() -> bool
        
        IsToolbar() returns true if the pane contains a toolbar.
        """
        ...
    
    def IsTopDockable(self):
        """
        IsTopDockable() -> bool
        
        IsTopDockable() returns true if the pane can be docked at the top of
        the managed frame.
        """
        ...
    
    def Layer(self, layer):
        """
        Layer(layer) -> AuiPaneInfo
        
        Layer() determines the layer of the docked pane.
        """
        ...
    
    def Left(self):
        """
        Left() -> AuiPaneInfo
        
        Left() sets the pane dock position to the left side of the frame.
        """
        ...
    
    def LeftDockable(self, b=...):
        """
        LeftDockable(b=True) -> AuiPaneInfo
        
        LeftDockable() indicates whether a pane can be docked on the left of
        the frame.
        """
        ...
    
    def MaximizeButton(self, visible=...):
        """
        MaximizeButton(visible=True) -> AuiPaneInfo
        
        MaximizeButton() indicates that a maximize button should be drawn for
        the pane.
        """
        ...
    
    def MinimizeButton(self, visible=...):
        """
        MinimizeButton(visible=True) -> AuiPaneInfo
        
        MinimizeButton() indicates that a minimize button should be drawn for
        the pane.
        """
        ...
    
    def Movable(self, b=...):
        """
        Movable(b=True) -> AuiPaneInfo
        
        Movable indicates whether a frame can be moved.
        """
        ...
    
    def Name(self, n):
        """
        Name(n) -> AuiPaneInfo
        
        Name() sets the name of the pane so it can be referenced in lookup
        functions.
        """
        ...
    
    def PaneBorder(self, visible=...):
        """
        PaneBorder(visible=True) -> AuiPaneInfo
        
        PaneBorder indicates that a border should be drawn for the pane.
        """
        ...
    
    def PinButton(self, visible=...):
        """
        PinButton(visible=True) -> AuiPaneInfo
        
        PinButton() indicates that a pin button should be drawn for the pane.
        """
        ...
    
    def Position(self, pos):
        """
        Position(pos) -> AuiPaneInfo
        
        Position() determines the position of the docked pane.
        """
        ...
    
    def Resizable(self, resizable=...):
        """
        Resizable(resizable=True) -> AuiPaneInfo
        
        Resizable() allows a pane to be resized if the parameter is true, and
        forces it to be a fixed size if the parameter is false.
        """
        ...
    
    def Right(self):
        """
        Right() -> AuiPaneInfo
        
        Right() sets the pane dock position to the right side of the frame.
        """
        ...
    
    def RightDockable(self, b=...):
        """
        RightDockable(b=True) -> AuiPaneInfo
        
        RightDockable() indicates whether a pane can be docked on the right of
        the frame.
        """
        ...
    
    def Row(self, row):
        """
        Row(row) -> AuiPaneInfo
        
        Row() determines the row of the docked pane.
        """
        ...
    
    def SafeSet(self, source):
        """
        SafeSet(source)
        
        Write the safe parts of a PaneInfo object "source" into "this".
        """
        ...
    
    def SetFlag(self, flag, option_state):
        """
        SetFlag(flag, option_state) -> AuiPaneInfo
        
        SetFlag() turns the property given by flag on or off with the
        option_state parameter.
        """
        ...
    
    def Show(self, show=...):
        """
        Show(show=True) -> AuiPaneInfo
        
        Show() indicates that a pane should be shown.
        """
        ...
    
    def ToolbarPane(self):
        """
        ToolbarPane() -> AuiPaneInfo
        
        ToolbarPane() specifies that the pane should adopt the default toolbar
        pane settings.
        """
        ...
    
    def Top(self):
        """
        Top() -> AuiPaneInfo
        
        Top() sets the pane dock position to the top of the frame.
        """
        ...
    
    def TopDockable(self, b=...):
        """
        TopDockable(b=True) -> AuiPaneInfo
        
        TopDockable() indicates whether a pane can be docked at the top of the
        frame.
        """
        ...
    
    def Window(self, w):
        """
        Window(w) -> AuiPaneInfo
        
        Window() assigns the window pointer that the wxAuiPaneInfo should use.
        """
        ...
    
    def IsValid(self):
        """
        IsValid() -> bool
        """
        ...
    


class AuiManagerEvent(wx.Event):
    """
    AuiManagerEvent(type=wx.wxEVT_NULL)
    
    Event used to indicate various actions taken with wxAuiManager.
    """
    def __init__(self, type=...) -> None:
        """
        AuiManagerEvent(type=wx.wxEVT_NULL)
        
        Event used to indicate various actions taken with wxAuiManager.
        """
        ...
    
    def CanVeto(self):
        """
        CanVeto() -> bool
        """
        ...
    
    def GetButton(self):
        """
        GetButton() -> int
        """
        ...
    
    def GetDC(self):
        """
        GetDC() -> wx.DC
        """
        ...
    
    def GetVeto(self):
        """
        GetVeto() -> bool
        """
        ...
    
    def GetManager(self):
        """
        GetManager() -> AuiManager
        """
        ...
    
    def GetPane(self):
        """
        GetPane() -> AuiPaneInfo
        """
        ...
    
    def SetButton(self, button):
        """
        SetButton(button)
        
        Sets the ID of the button clicked that triggered this event.
        """
        ...
    
    def SetCanVeto(self, can_veto):
        """
        SetCanVeto(can_veto)
        
        Sets whether or not this event can be vetoed.
        """
        ...
    
    def SetDC(self, pdc):
        """
        SetDC(pdc)
        """
        ...
    
    def SetManager(self, manager):
        """
        SetManager(manager)
        
        Sets the wxAuiManager this event is associated with.
        """
        ...
    
    def SetPane(self, pane):
        """
        SetPane(pane)
        
        Sets the pane this event is associated with.
        """
        ...
    
    def Veto(self, veto=...):
        """
        Veto(veto=True)
        
        Cancels the action indicated by this event if CanVeto() is true.
        """
        ...
    
    Button = ...
    DC = ...
    Manager = ...
    Pane = ...


class AuiDockInfo:
    """
    AuiDockInfo()
    AuiDockInfo(c)
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiDockInfo()
        AuiDockInfo(c)
        """
        ...
    
    panes = ...
    rect = ...
    dock_direction = ...
    dock_layer = ...
    dock_row = ...
    size = ...
    min_size = ...
    resizable = ...
    toolbar = ...
    fixed = ...
    reserved1 = ...
    def IsOk(self):
        """
        IsOk() -> bool
        """
        ...
    
    def IsHorizontal(self):
        """
        IsHorizontal() -> bool
        """
        ...
    
    def IsVertical(self):
        """
        IsVertical() -> bool
        """
        ...
    


class AuiDockUIPart:
    """
    
    """
    typeCaption = ...
    typeGripper = ...
    typeDock = ...
    typeDockSizer = ...
    typePane = ...
    typePaneSizer = ...
    typeBackground = ...
    typePaneBorder = ...
    typePaneButton = ...
    type = ...
    orientation = ...
    dock = ...
    pane = ...
    button = ...
    cont_sizer = ...
    sizer_item = ...
    rect = ...


class AuiFloatingFrame(wx.Frame):
    """
    AuiFloatingFrame(parent, ownerMgr, pane, id=wx.ID_ANY, style=wx.RESIZE_BORDER|wx.SYSTEM_MENU|wx.CAPTION|wx.FRAME_NO_TASKBAR|wx.FRAME_FLOAT_ON_PARENT|wx.CLIP_CHILDREN)
    """
    def __init__(self, parent, ownerMgr, pane, id=..., style=...) -> None:
        """
        AuiFloatingFrame(parent, ownerMgr, pane, id=wx.ID_ANY, style=wx.RESIZE_BORDER|wx.SYSTEM_MENU|wx.CAPTION|wx.FRAME_NO_TASKBAR|wx.FRAME_FLOAT_ON_PARENT|wx.CLIP_CHILDREN)
        """
        ...
    
    def SetPaneWindow(self, pane):
        """
        SetPaneWindow(pane)
        """
        ...
    
    def GetOwnerManager(self):
        """
        GetOwnerManager() -> AuiManager
        """
        ...
    
    def GetAuiManager(self):
        """
        GetAuiManager() -> AuiManager
        
        Returns the embedded wxAuiManager managing this floating pane's
        contents.
        """
        ...
    
    AuiManager = ...
    OwnerManager = ...


EVT_AUI_PANE_BUTTON = ...
EVT_AUI_PANE_CLOSE = ...
EVT_AUI_PANE_MAXIMIZE = ...
EVT_AUI_PANE_RESTORE = ...
EVT_AUI_PANE_ACTIVATED = ...
EVT_AUI_RENDER = ...
EVT_AUI_FIND_MANAGER = ...
AUI_DOCKART_SASH_SIZE = ...
AUI_DOCKART_CAPTION_SIZE = ...
AUI_DOCKART_GRIPPER_SIZE = ...
AUI_DOCKART_PANE_BORDER_SIZE = ...
AUI_DOCKART_PANE_BUTTON_SIZE = ...
AUI_DOCKART_BACKGROUND_COLOUR = ...
AUI_DOCKART_SASH_COLOUR = ...
AUI_DOCKART_ACTIVE_CAPTION_COLOUR = ...
AUI_DOCKART_ACTIVE_CAPTION_GRADIENT_COLOUR = ...
AUI_DOCKART_INACTIVE_CAPTION_COLOUR = ...
AUI_DOCKART_INACTIVE_CAPTION_GRADIENT_COLOUR = ...
AUI_DOCKART_ACTIVE_CAPTION_TEXT_COLOUR = ...
AUI_DOCKART_INACTIVE_CAPTION_TEXT_COLOUR = ...
AUI_DOCKART_BORDER_COLOUR = ...
AUI_DOCKART_GRIPPER_COLOUR = ...
AUI_DOCKART_CAPTION_FONT = ...
AUI_DOCKART_GRADIENT_TYPE = ...
AUI_GRADIENT_NONE = ...
AUI_GRADIENT_VERTICAL = ...
AUI_GRADIENT_HORIZONTAL = ...
AUI_BUTTON_STATE_NORMAL = ...
AUI_BUTTON_STATE_HOVER = ...
AUI_BUTTON_STATE_PRESSED = ...
AUI_BUTTON_STATE_DISABLED = ...
AUI_BUTTON_STATE_HIDDEN = ...
AUI_BUTTON_STATE_CHECKED = ...
AUI_BUTTON_CLOSE = ...
AUI_BUTTON_MAXIMIZE_RESTORE = ...
AUI_BUTTON_MINIMIZE = ...
AUI_BUTTON_PIN = ...
AUI_BUTTON_OPTIONS = ...
AUI_BUTTON_WINDOWLIST = ...
AUI_BUTTON_LEFT = ...
AUI_BUTTON_RIGHT = ...
AUI_BUTTON_UP = ...
AUI_BUTTON_DOWN = ...
AUI_BUTTON_CUSTOM1 = ...
AUI_BUTTON_CUSTOM2 = ...
AUI_BUTTON_CUSTOM3 = ...
class AuiDockArt:
    """
    AuiDockArt()
    
    wxAuiDockArt is part of the wxAUI class framework.
    """
    def __init__(self) -> None:
        """
        AuiDockArt()
        
        wxAuiDockArt is part of the wxAUI class framework.
        """
        ...
    
    def Clone(self):
        """
        Clone() -> AuiDockArt
        
        Create a copy of this wxAuiDockArt instance.
        """
        ...
    
    def DrawBackground(self, dc, window, orientation, rect):
        """
        DrawBackground(dc, window, orientation, rect)
        
        Draws a background.
        """
        ...
    
    def DrawBorder(self, dc, window, rect, pane):
        """
        DrawBorder(dc, window, rect, pane)
        
        Draws a border.
        """
        ...
    
    def DrawCaption(self, dc, window, text, rect, pane):
        """
        DrawCaption(dc, window, text, rect, pane)
        
        Draws a caption.
        """
        ...
    
    def DrawGripper(self, dc, window, rect, pane):
        """
        DrawGripper(dc, window, rect, pane)
        
        Draws a gripper.
        """
        ...
    
    def DrawPaneButton(self, dc, window, button, button_state, rect, pane):
        """
        DrawPaneButton(dc, window, button, button_state, rect, pane)
        
        Draws a button in the pane's title bar.
        """
        ...
    
    def DrawSash(self, dc, window, orientation, rect):
        """
        DrawSash(dc, window, orientation, rect)
        
        Draws a sash between two windows.
        """
        ...
    
    def GetColour(self, id):
        """
        GetColour(id) -> wx.Colour
        
        Get the colour of a certain setting.
        """
        ...
    
    def GetFont(self, id):
        """
        GetFont(id) -> wx.Font
        
        Get a font setting.
        """
        ...
    
    def GetMetric(self, id):
        """
        GetMetric(id) -> int
        
        Get the value of a certain setting.
        """
        ...
    
    def SetColour(self, id, colour):
        """
        SetColour(id, colour)
        
        Set a certain setting with the value colour.
        """
        ...
    
    def SetFont(self, id, font):
        """
        SetFont(id, font)
        
        Set a font setting.
        """
        ...
    
    def SetMetric(self, id, new_val):
        """
        SetMetric(id, new_val)
        
        Set a certain setting with the value new_val.
        """
        ...
    


class AuiDefaultDockArt(AuiDockArt):
    """
    AuiDefaultDockArt()
    
    This is the default art provider for wxAuiManager.
    """
    def __init__(self) -> None:
        """
        AuiDefaultDockArt()
        
        This is the default art provider for wxAuiManager.
        """
        ...
    
    def Clone(self):
        """
        Clone() -> AuiDockArt
        
        Create a copy of this wxAuiDockArt instance.
        """
        ...
    
    def GetMetric(self, id):
        """
        GetMetric(id) -> int
        
        Get the value of a certain setting.
        """
        ...
    
    def SetMetric(self, id, new_val):
        """
        SetMetric(id, new_val)
        
        Set a certain setting with the value new_val.
        """
        ...
    
    def GetColour(self, id):
        """
        GetColour(id) -> wx.Colour
        
        Get the colour of a certain setting.
        """
        ...
    
    def SetColour(self, id, colour):
        """
        SetColour(id, colour)
        
        Set a certain setting with the value colour.
        """
        ...
    
    def SetFont(self, id, font):
        """
        SetFont(id, font)
        
        Set a font setting.
        """
        ...
    
    def GetFont(self, id):
        """
        GetFont(id) -> wx.Font
        
        Get a font setting.
        """
        ...
    
    def DrawSash(self, dc, window, orientation, rect):
        """
        DrawSash(dc, window, orientation, rect)
        
        Draws a sash between two windows.
        """
        ...
    
    def DrawBackground(self, dc, window, orientation, rect):
        """
        DrawBackground(dc, window, orientation, rect)
        
        Draws a background.
        """
        ...
    
    def DrawCaption(self, dc, window, text, rect, pane):
        """
        DrawCaption(dc, window, text, rect, pane)
        
        Draws a caption.
        """
        ...
    
    def DrawGripper(self, dc, window, rect, pane):
        """
        DrawGripper(dc, window, rect, pane)
        
        Draws a gripper.
        """
        ...
    
    def DrawBorder(self, dc, window, rect, pane):
        """
        DrawBorder(dc, window, rect, pane)
        
        Draws a border.
        """
        ...
    
    def DrawPaneButton(self, dc, window, button, button_state, rect, pane):
        """
        DrawPaneButton(dc, window, button, button_state, rect, pane)
        
        Draws a button in the pane's title bar.
        """
        ...
    
    def DrawIcon(self, dc, rect, pane):
        """
        DrawIcon(dc, rect, pane)
        """
        ...
    


AUI_TB_TEXT = ...
AUI_TB_NO_TOOLTIPS = ...
AUI_TB_NO_AUTORESIZE = ...
AUI_TB_GRIPPER = ...
AUI_TB_OVERFLOW = ...
AUI_TB_VERTICAL = ...
AUI_TB_HORZ_LAYOUT = ...
AUI_TB_HORIZONTAL = ...
AUI_TB_PLAIN_BACKGROUND = ...
AUI_TB_HORZ_TEXT = ...
AUI_ORIENTATION_MASK = ...
AUI_TB_DEFAULT_STYLE = ...
AUI_TBART_SEPARATOR_SIZE = ...
AUI_TBART_GRIPPER_SIZE = ...
AUI_TBART_OVERFLOW_SIZE = ...
AUI_TBTOOL_TEXT_LEFT = ...
AUI_TBTOOL_TEXT_RIGHT = ...
AUI_TBTOOL_TEXT_TOP = ...
AUI_TBTOOL_TEXT_BOTTOM = ...
wxEVT_AUITOOLBAR_TOOL_DROPDOWN = ...
wxEVT_AUITOOLBAR_OVERFLOW_CLICK = ...
wxEVT_AUITOOLBAR_RIGHT_CLICK = ...
wxEVT_AUITOOLBAR_MIDDLE_CLICK = ...
wxEVT_AUITOOLBAR_BEGIN_DRAG = ...
class AuiToolBarItem:
    """
    AuiToolBarItem()
    AuiToolBarItem(c)
    
    wxAuiToolBarItem is part of the wxAUI class framework, representing a
    toolbar element.
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiToolBarItem()
        AuiToolBarItem(c)
        
        wxAuiToolBarItem is part of the wxAUI class framework, representing a
        toolbar element.
        """
        ...
    
    def Assign(self, c):
        """
        Assign(c)
        
        Assigns the properties of the wxAuiToolBarItem "c" to this.
        """
        ...
    
    def SetWindow(self, w):
        """
        SetWindow(w)
        
        Assigns a window to the toolbar item.
        """
        ...
    
    def GetWindow(self):
        """
        GetWindow() -> wx.Window
        
        Returns the wxWindow* associated to the toolbar item.
        """
        ...
    
    def SetId(self, new_id):
        """
        SetId(new_id)
        
        Sets the toolbar item identifier.
        """
        ...
    
    def GetId(self):
        """
        GetId() -> int
        
        Returns the toolbar item identifier.
        """
        ...
    
    def SetKind(self, new_kind):
        """
        SetKind(new_kind)
        
        Sets the wxAuiToolBarItem kind.
        """
        ...
    
    def GetKind(self):
        """
        GetKind() -> int
        
        Returns the toolbar item kind.
        """
        ...
    
    def SetState(self, new_state):
        """
        SetState(new_state)
        
        Set the current state of the toolbar item.
        """
        ...
    
    def GetState(self):
        """
        GetState() -> int
        
        Gets the current state of the toolbar item.
        """
        ...
    
    def SetSizerItem(self, s):
        """
        SetSizerItem(s)
        """
        ...
    
    def GetSizerItem(self):
        """
        GetSizerItem() -> wx.SizerItem
        """
        ...
    
    def SetLabel(self, s):
        """
        SetLabel(s)
        """
        ...
    
    def GetLabel(self):
        """
        GetLabel() -> String
        """
        ...
    
    def SetBitmap(self, bmp):
        """
        SetBitmap(bmp)
        """
        ...
    
    def GetBitmap(self):
        """
        GetBitmap() -> wx.Bitmap
        """
        ...
    
    def SetDisabledBitmap(self, bmp):
        """
        SetDisabledBitmap(bmp)
        """
        ...
    
    def GetDisabledBitmap(self):
        """
        GetDisabledBitmap() -> wx.Bitmap
        """
        ...
    
    def SetHoverBitmap(self, bmp):
        """
        SetHoverBitmap(bmp)
        """
        ...
    
    def GetHoverBitmap(self):
        """
        GetHoverBitmap() -> wx.Bitmap
        """
        ...
    
    def SetShortHelp(self, s):
        """
        SetShortHelp(s)
        """
        ...
    
    def GetShortHelp(self):
        """
        GetShortHelp() -> String
        """
        ...
    
    def SetLongHelp(self, s):
        """
        SetLongHelp(s)
        """
        ...
    
    def GetLongHelp(self):
        """
        GetLongHelp() -> String
        """
        ...
    
    def SetMinSize(self, s):
        """
        SetMinSize(s)
        """
        ...
    
    def GetMinSize(self):
        """
        GetMinSize() -> wx.Size
        """
        ...
    
    def SetSpacerPixels(self, s):
        """
        SetSpacerPixels(s)
        """
        ...
    
    def GetSpacerPixels(self):
        """
        GetSpacerPixels() -> int
        """
        ...
    
    def SetProportion(self, p):
        """
        SetProportion(p)
        """
        ...
    
    def GetProportion(self):
        """
        GetProportion() -> int
        """
        ...
    
    def SetActive(self, b):
        """
        SetActive(b)
        """
        ...
    
    def IsActive(self):
        """
        IsActive() -> bool
        """
        ...
    
    def SetHasDropDown(self, b):
        """
        SetHasDropDown(b)
        
        Set whether this tool has a drop down button.
        """
        ...
    
    def HasDropDown(self):
        """
        HasDropDown() -> bool
        
        Returns whether the toolbar item has an associated drop down button.
        """
        ...
    
    def SetSticky(self, b):
        """
        SetSticky(b)
        """
        ...
    
    def IsSticky(self):
        """
        IsSticky() -> bool
        """
        ...
    
    def SetUserData(self, l):
        """
        SetUserData(l)
        """
        ...
    
    def GetUserData(self):
        """
        GetUserData() -> long
        """
        ...
    
    def SetAlignment(self, l):
        """
        SetAlignment(l)
        """
        ...
    
    def GetAlignment(self):
        """
        GetAlignment() -> int
        """
        ...
    
    def CanBeToggled(self):
        """
        CanBeToggled() -> bool
        
        Returns whether the toolbar item can be toggled.
        """
        ...
    
    Alignment = ...
    Bitmap = ...
    DisabledBitmap = ...
    HoverBitmap = ...
    Id = ...
    Kind = ...
    Label = ...
    LongHelp = ...
    MinSize = ...
    Proportion = ...
    ShortHelp = ...
    SizerItem = ...
    SpacerPixels = ...
    State = ...
    UserData = ...
    Window = ...


class AuiToolBarArt:
    """
    AuiToolBarArt()
    
    wxAuiToolBarArt is part of the wxAUI class framework.
    """
    def __init__(self) -> None:
        """
        AuiToolBarArt()
        
        wxAuiToolBarArt is part of the wxAUI class framework.
        """
        ...
    
    def Clone(self):
        """
        Clone() -> AuiToolBarArt
        """
        ...
    
    def SetFlags(self, flags):
        """
        SetFlags(flags)
        """
        ...
    
    def GetFlags(self):
        """
        GetFlags() -> unsignedint
        """
        ...
    
    def SetFont(self, font):
        """
        SetFont(font)
        """
        ...
    
    def GetFont(self):
        """
        GetFont() -> wx.Font
        """
        ...
    
    def SetTextOrientation(self, orientation):
        """
        SetTextOrientation(orientation)
        """
        ...
    
    def GetTextOrientation(self):
        """
        GetTextOrientation() -> int
        """
        ...
    
    def DrawBackground(self, dc, wnd, rect):
        """
        DrawBackground(dc, wnd, rect)
        """
        ...
    
    def DrawPlainBackground(self, dc, wnd, rect):
        """
        DrawPlainBackground(dc, wnd, rect)
        """
        ...
    
    def DrawLabel(self, dc, wnd, item, rect):
        """
        DrawLabel(dc, wnd, item, rect)
        """
        ...
    
    def DrawButton(self, dc, wnd, item, rect):
        """
        DrawButton(dc, wnd, item, rect)
        """
        ...
    
    def DrawDropDownButton(self, dc, wnd, item, rect):
        """
        DrawDropDownButton(dc, wnd, item, rect)
        """
        ...
    
    def DrawControlLabel(self, dc, wnd, item, rect):
        """
        DrawControlLabel(dc, wnd, item, rect)
        """
        ...
    
    def DrawSeparator(self, dc, wnd, rect):
        """
        DrawSeparator(dc, wnd, rect)
        """
        ...
    
    def DrawGripper(self, dc, wnd, rect):
        """
        DrawGripper(dc, wnd, rect)
        """
        ...
    
    def DrawOverflowButton(self, dc, wnd, rect, state):
        """
        DrawOverflowButton(dc, wnd, rect, state)
        """
        ...
    
    def GetLabelSize(self, dc, wnd, item):
        """
        GetLabelSize(dc, wnd, item) -> wx.Size
        """
        ...
    
    def GetToolSize(self, dc, wnd, item):
        """
        GetToolSize(dc, wnd, item) -> wx.Size
        """
        ...
    
    def GetElementSize(self, element_id):
        """
        GetElementSize(element_id) -> int
        """
        ...
    
    def SetElementSize(self, element_id, size):
        """
        SetElementSize(element_id, size)
        """
        ...
    
    def ShowDropDown(self, wnd, items):
        """
        ShowDropDown(wnd, items) -> int
        """
        ...
    
    Flags = ...
    Font = ...
    TextOrientation = ...


class AuiDefaultToolBarArt(AuiToolBarArt):
    """
    AuiDefaultToolBarArt()
    
    wxAuiDefaultToolBarArt is part of the wxAUI class framework.
    """
    def __init__(self) -> None:
        """
        AuiDefaultToolBarArt()
        
        wxAuiDefaultToolBarArt is part of the wxAUI class framework.
        """
        ...
    
    def Clone(self):
        """
        Clone() -> AuiToolBarArt
        """
        ...
    
    def SetFlags(self, flags):
        """
        SetFlags(flags)
        """
        ...
    
    def GetFlags(self):
        """
        GetFlags() -> unsignedint
        """
        ...
    
    def SetFont(self, font):
        """
        SetFont(font)
        """
        ...
    
    def GetFont(self):
        """
        GetFont() -> wx.Font
        """
        ...
    
    def SetTextOrientation(self, orientation):
        """
        SetTextOrientation(orientation)
        """
        ...
    
    def GetTextOrientation(self):
        """
        GetTextOrientation() -> int
        """
        ...
    
    def DrawBackground(self, dc, wnd, rect):
        """
        DrawBackground(dc, wnd, rect)
        """
        ...
    
    def DrawPlainBackground(self, dc, wnd, rect):
        """
        DrawPlainBackground(dc, wnd, rect)
        """
        ...
    
    def DrawLabel(self, dc, wnd, item, rect):
        """
        DrawLabel(dc, wnd, item, rect)
        """
        ...
    
    def DrawButton(self, dc, wnd, item, rect):
        """
        DrawButton(dc, wnd, item, rect)
        """
        ...
    
    def DrawDropDownButton(self, dc, wnd, item, rect):
        """
        DrawDropDownButton(dc, wnd, item, rect)
        """
        ...
    
    def DrawControlLabel(self, dc, wnd, item, rect):
        """
        DrawControlLabel(dc, wnd, item, rect)
        """
        ...
    
    def DrawSeparator(self, dc, wnd, rect):
        """
        DrawSeparator(dc, wnd, rect)
        """
        ...
    
    def DrawGripper(self, dc, wnd, rect):
        """
        DrawGripper(dc, wnd, rect)
        """
        ...
    
    def DrawOverflowButton(self, dc, wnd, rect, state):
        """
        DrawOverflowButton(dc, wnd, rect, state)
        """
        ...
    
    def GetLabelSize(self, dc, wnd, item):
        """
        GetLabelSize(dc, wnd, item) -> wx.Size
        """
        ...
    
    def GetToolSize(self, dc, wnd, item):
        """
        GetToolSize(dc, wnd, item) -> wx.Size
        """
        ...
    
    def GetElementSize(self, element):
        """
        GetElementSize(element) -> int
        """
        ...
    
    def SetElementSize(self, element_id, size):
        """
        SetElementSize(element_id, size)
        """
        ...
    
    def ShowDropDown(self, wnd, items):
        """
        ShowDropDown(wnd, items) -> int
        """
        ...
    
    Flags = ...
    Font = ...
    TextOrientation = ...


class AuiToolBar(wx.Control):
    """
    AuiToolBar()
    AuiToolBar(parent, id=wx.ID_ANY, position=wx.DefaultPosition, size=wx.DefaultSize, style=AUI_TB_DEFAULT_STYLE)
    
    wxAuiToolBar is a dockable toolbar, part of the wxAUI class framework.
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiToolBar()
        AuiToolBar(parent, id=wx.ID_ANY, position=wx.DefaultPosition, size=wx.DefaultSize, style=AUI_TB_DEFAULT_STYLE)
        
        wxAuiToolBar is a dockable toolbar, part of the wxAUI class framework.
        """
        ...
    
    def Create(self, parent, id=..., pos=..., size=..., style=...):
        """
        Create(parent, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, style=AUI_TB_DEFAULT_STYLE) -> bool
        
        Really create wxAuiToolBar created using default constructor.
        """
        ...
    
    def SetWindowStyleFlag(self, style):
        """
        SetWindowStyleFlag(style)
        
        Sets the style of the window.
        """
        ...
    
    def GetWindowStyleFlag(self):
        """
        GetWindowStyleFlag() -> long
        
        Gets the window style that was passed to the constructor or Create()
        method.
        """
        ...
    
    def SetArtProvider(self, art):
        """
        SetArtProvider(art)
        """
        ...
    
    def GetArtProvider(self):
        """
        GetArtProvider() -> AuiToolBarArt
        """
        ...
    
    def SetFont(self, font):
        """
        SetFont(font) -> bool
        
        Sets the font for this window.
        """
        ...
    
    def AddTool(self, *args, **kw):
        """
        AddTool(toolId, label, bitmap, short_help_string=wx.EmptyString, kind=wx.ITEM_NORMAL) -> AuiToolBarItem
        AddTool(toolId, label, bitmap, disabled_bitmap, kind, short_help_string, long_help_string, client_data) -> AuiToolBarItem
        AddTool(toolId, bitmap, disabled_bitmap, toggle=False, client_data=None, short_help_string=wx.EmptyString, long_help_string=wx.EmptyString) -> AuiToolBarItem
        """
        ...
    
    def AddLabel(self, toolId, label=..., width=...):
        """
        AddLabel(toolId, label=wx.EmptyString, width=-1) -> AuiToolBarItem
        """
        ...
    
    def AddControl(self, control, label=...):
        """
        AddControl(control, label=wx.EmptyString) -> AuiToolBarItem
        """
        ...
    
    def AddSeparator(self):
        """
        AddSeparator() -> AuiToolBarItem
        """
        ...
    
    def AddSpacer(self, pixels):
        """
        AddSpacer(pixels) -> AuiToolBarItem
        """
        ...
    
    def AddStretchSpacer(self, proportion=...):
        """
        AddStretchSpacer(proportion=1) -> AuiToolBarItem
        """
        ...
    
    def Realize(self):
        """
        Realize() -> bool
        """
        ...
    
    def FindControl(self, window_id):
        """
        FindControl(window_id) -> wx.Control
        """
        ...
    
    def FindToolByPosition(self, x, y):
        """
        FindToolByPosition(x, y) -> AuiToolBarItem
        """
        ...
    
    def FindToolByIndex(self, idx):
        """
        FindToolByIndex(idx) -> AuiToolBarItem
        """
        ...
    
    def FindTool(self, toolId):
        """
        FindTool(toolId) -> AuiToolBarItem
        """
        ...
    
    def ClearTools(self):
        """
        ClearTools()
        """
        ...
    
    def Clear(self):
        """
        Clear()
        """
        ...
    
    def DestroyTool(self, toolId):
        """
        DestroyTool(toolId) -> bool
        
        Destroys the tool with the given ID and its associated window, if any.
        """
        ...
    
    def DestroyToolByIndex(self, idx):
        """
        DestroyToolByIndex(idx) -> bool
        
        Destroys the tool at the given position and its associated window, if
        any.
        """
        ...
    
    def DeleteTool(self, toolId):
        """
        DeleteTool(toolId) -> bool
        
        Removes the tool with the given ID from the toolbar.
        """
        ...
    
    def DeleteByIndex(self, idx):
        """
        DeleteByIndex(idx) -> bool
        
        Removes the tool at the given position from the toolbar.
        """
        ...
    
    def GetToolCount(self):
        """
        GetToolCount() -> size_t
        """
        ...
    
    def GetToolPos(self, toolId):
        """
        GetToolPos(toolId) -> int
        """
        ...
    
    def GetToolIndex(self, toolId):
        """
        GetToolIndex(toolId) -> int
        """
        ...
    
    def GetToolFits(self, toolId):
        """
        GetToolFits(toolId) -> bool
        """
        ...
    
    def GetToolRect(self, toolId):
        """
        GetToolRect(toolId) -> wx.Rect
        """
        ...
    
    def GetToolFitsByIndex(self, toolId):
        """
        GetToolFitsByIndex(toolId) -> bool
        """
        ...
    
    def GetToolBarFits(self):
        """
        GetToolBarFits() -> bool
        """
        ...
    
    def SetMargins(self, *args, **kw):
        """
        SetMargins(size)
        SetMargins(x, y)
        SetMargins(left, right, top, bottom)
        """
        ...
    
    def SetToolBitmapSize(self, size):
        """
        SetToolBitmapSize(size)
        """
        ...
    
    def GetToolBitmapSize(self):
        """
        GetToolBitmapSize() -> wx.Size
        """
        ...
    
    def GetOverflowVisible(self):
        """
        GetOverflowVisible() -> bool
        """
        ...
    
    def SetOverflowVisible(self, visible):
        """
        SetOverflowVisible(visible)
        """
        ...
    
    def GetGripperVisible(self):
        """
        GetGripperVisible() -> bool
        """
        ...
    
    def SetGripperVisible(self, visible):
        """
        SetGripperVisible(visible)
        """
        ...
    
    def ToggleTool(self, toolId, state):
        """
        ToggleTool(toolId, state)
        """
        ...
    
    def GetToolToggled(self, toolId):
        """
        GetToolToggled(toolId) -> bool
        """
        ...
    
    def EnableTool(self, toolId, state):
        """
        EnableTool(toolId, state)
        """
        ...
    
    def GetToolEnabled(self, toolId):
        """
        GetToolEnabled(toolId) -> bool
        """
        ...
    
    def SetToolDropDown(self, toolId, dropdown):
        """
        SetToolDropDown(toolId, dropdown)
        
        Set whether the specified toolbar item has a drop down button.
        """
        ...
    
    def GetToolDropDown(self, toolId):
        """
        GetToolDropDown(toolId) -> bool
        
        Returns whether the specified toolbar item has an associated drop down
        button.
        """
        ...
    
    def SetToolBorderPadding(self, padding):
        """
        SetToolBorderPadding(padding)
        """
        ...
    
    def GetToolBorderPadding(self):
        """
        GetToolBorderPadding() -> int
        """
        ...
    
    def SetToolTextOrientation(self, orientation):
        """
        SetToolTextOrientation(orientation)
        """
        ...
    
    def GetToolTextOrientation(self):
        """
        GetToolTextOrientation() -> int
        """
        ...
    
    def SetToolPacking(self, packing):
        """
        SetToolPacking(packing)
        """
        ...
    
    def GetToolPacking(self):
        """
        GetToolPacking() -> int
        """
        ...
    
    def SetToolProportion(self, toolId, proportion):
        """
        SetToolProportion(toolId, proportion)
        """
        ...
    
    def GetToolProportion(self, toolId):
        """
        GetToolProportion(toolId) -> int
        """
        ...
    
    def SetToolSeparation(self, separation):
        """
        SetToolSeparation(separation)
        """
        ...
    
    def GetToolSeparation(self):
        """
        GetToolSeparation() -> int
        """
        ...
    
    def SetToolSticky(self, toolId, sticky):
        """
        SetToolSticky(toolId, sticky)
        """
        ...
    
    def GetToolSticky(self, toolId):
        """
        GetToolSticky(toolId) -> bool
        """
        ...
    
    def GetToolLabel(self, toolId):
        """
        GetToolLabel(toolId) -> String
        """
        ...
    
    def SetToolLabel(self, toolId, label):
        """
        SetToolLabel(toolId, label)
        """
        ...
    
    def GetToolBitmap(self, toolId):
        """
        GetToolBitmap(toolId) -> wx.Bitmap
        """
        ...
    
    def SetToolBitmap(self, toolId, bitmap):
        """
        SetToolBitmap(toolId, bitmap)
        """
        ...
    
    def GetToolShortHelp(self, toolId):
        """
        GetToolShortHelp(toolId) -> String
        """
        ...
    
    def SetToolShortHelp(self, toolId, help_string):
        """
        SetToolShortHelp(toolId, help_string)
        """
        ...
    
    def GetToolLongHelp(self, toolId):
        """
        GetToolLongHelp(toolId) -> String
        """
        ...
    
    def SetToolLongHelp(self, toolId, help_string):
        """
        SetToolLongHelp(toolId, help_string)
        """
        ...
    
    def SetCustomOverflowItems(self, prepend, append):
        """
        SetCustomOverflowItems(prepend, append)
        
        Add toolbar items that are always displayed in the overflow menu.
        """
        ...
    
    def GetHintSize(self, dock_direction):
        """
        GetHintSize(dock_direction) -> wx.Size
        
        get size of hint rectangle for a particular dock location
        """
        ...
    
    def IsPaneValid(self, pane):
        """
        IsPaneValid(pane) -> bool
        """
        ...
    
    @staticmethod
    def GetClassDefaultAttributes(variant=...):
        """
        GetClassDefaultAttributes(variant=wx.WINDOW_VARIANT_NORMAL) -> wx.VisualAttributes
        """
        ...
    
    ArtProvider = ...
    GripperVisible = ...
    OverflowVisible = ...
    ToolBarFits = ...
    ToolBitmapSize = ...
    ToolBorderPadding = ...
    ToolCount = ...
    ToolPacking = ...
    ToolSeparation = ...
    ToolTextOrientation = ...
    WindowStyleFlag = ...


class AuiToolBarEvent(wx.NotifyEvent):
    """
    AuiToolBarEvent(commandType=wx.wxEVT_NULL, winId=0)
    AuiToolBarEvent(c)
    
    wxAuiToolBarEvent is used for the events generated by wxAuiToolBar.
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiToolBarEvent(commandType=wx.wxEVT_NULL, winId=0)
        AuiToolBarEvent(c)
        
        wxAuiToolBarEvent is used for the events generated by wxAuiToolBar.
        """
        ...
    
    def IsDropDownClicked(self):
        """
        IsDropDownClicked() -> bool
        
        Returns whether the drop down menu has been clicked.
        """
        ...
    
    def GetClickPoint(self):
        """
        GetClickPoint() -> wx.Point
        
        Returns the point where the user clicked with the mouse.
        """
        ...
    
    def GetItemRect(self):
        """
        GetItemRect() -> wx.Rect
        
        Returns the wxAuiToolBarItem rectangle bounding the mouse click point.
        """
        ...
    
    def GetToolId(self):
        """
        GetToolId() -> int
        
        Returns the wxAuiToolBarItem identifier.
        """
        ...
    
    def SetDropDownClicked(self, c):
        """
        SetDropDownClicked(c)
        """
        ...
    
    def SetClickPoint(self, p):
        """
        SetClickPoint(p)
        """
        ...
    
    def SetItemRect(self, r):
        """
        SetItemRect(r)
        """
        ...
    
    def SetToolId(self, toolId):
        """
        SetToolId(toolId)
        """
        ...
    
    ClickPoint = ...
    ItemRect = ...
    ToolId = ...


EVT_AUITOOLBAR_TOOL_DROPDOWN = ...
EVT_AUITOOLBAR_OVERFLOW_CLICK = ...
EVT_AUITOOLBAR_RIGHT_CLICK = ...
EVT_AUITOOLBAR_MIDDLE_CLICK = ...
EVT_AUITOOLBAR_BEGIN_DRAG = ...
AUI_NB_TOP = ...
AUI_NB_LEFT = ...
AUI_NB_RIGHT = ...
AUI_NB_BOTTOM = ...
AUI_NB_TAB_SPLIT = ...
AUI_NB_TAB_MOVE = ...
AUI_NB_TAB_EXTERNAL_MOVE = ...
AUI_NB_TAB_FIXED_WIDTH = ...
AUI_NB_SCROLL_BUTTONS = ...
AUI_NB_WINDOWLIST_BUTTON = ...
AUI_NB_CLOSE_BUTTON = ...
AUI_NB_CLOSE_ON_ACTIVE_TAB = ...
AUI_NB_CLOSE_ON_ALL_TABS = ...
AUI_NB_MIDDLE_CLICK_CLOSE = ...
AUI_NB_DEFAULT_STYLE = ...
wxEVT_AUINOTEBOOK_PAGE_CLOSE = ...
wxEVT_AUINOTEBOOK_PAGE_CHANGED = ...
wxEVT_AUINOTEBOOK_PAGE_CHANGING = ...
wxEVT_AUINOTEBOOK_PAGE_CLOSED = ...
wxEVT_AUINOTEBOOK_BUTTON = ...
wxEVT_AUINOTEBOOK_BEGIN_DRAG = ...
wxEVT_AUINOTEBOOK_END_DRAG = ...
wxEVT_AUINOTEBOOK_DRAG_MOTION = ...
wxEVT_AUINOTEBOOK_ALLOW_DND = ...
wxEVT_AUINOTEBOOK_TAB_MIDDLE_DOWN = ...
wxEVT_AUINOTEBOOK_TAB_MIDDLE_UP = ...
wxEVT_AUINOTEBOOK_TAB_RIGHT_DOWN = ...
wxEVT_AUINOTEBOOK_TAB_RIGHT_UP = ...
wxEVT_AUINOTEBOOK_DRAG_DONE = ...
wxEVT_AUINOTEBOOK_BG_DCLICK = ...
class AuiNotebook(wx.BookCtrlBase):
    """
    AuiNotebook()
    AuiNotebook(parent, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, style=AUI_NB_DEFAULT_STYLE)
    
    wxAuiNotebook is part of the wxAUI class framework, which represents a
    notebook control, managing multiple windows with associated tabs.
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiNotebook()
        AuiNotebook(parent, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, style=AUI_NB_DEFAULT_STYLE)
        
        wxAuiNotebook is part of the wxAUI class framework, which represents a
        notebook control, managing multiple windows with associated tabs.
        """
        ...
    
    def AddPage(self, *args, **kw):
        """
        AddPage(page, caption, select=False, bitmap=wx.BitmapBundle()) -> bool
        AddPage(page, text, select, imageId) -> bool
        
        Adds a page.
        """
        ...
    
    def AdvanceSelection(self, forward=...):
        """
        AdvanceSelection(forward=True)
        
        Sets the selection to the next or previous page.
        """
        ...
    
    def ChangeSelection(self, n):
        """
        ChangeSelection(n) -> int
        
        Changes the selection for the given page, returning the previous
        selection.
        """
        ...
    
    def Create(self, parent, id=..., pos=..., size=..., style=...):
        """
        Create(parent, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, style=0) -> bool
        
        Creates the notebook window.
        """
        ...
    
    def DeleteAllPages(self):
        """
        DeleteAllPages() -> bool
        
        Deletes all pages.
        """
        ...
    
    def DeletePage(self, page):
        """
        DeletePage(page) -> bool
        
        Deletes a page at the given index.
        """
        ...
    
    def GetArtProvider(self):
        """
        GetArtProvider() -> AuiTabArt
        
        Returns the associated art provider.
        """
        ...
    
    def GetCurrentPage(self):
        """
        GetCurrentPage() -> wx.Window
        
        Returns the currently selected page or NULL.
        """
        ...
    
    def GetHeightForPageHeight(self, pageHeight):
        """
        GetHeightForPageHeight(pageHeight) -> int
        
        Returns the desired height of the notebook for the given page height.
        """
        ...
    
    def GetPage(self, page_idx):
        """
        GetPage(page_idx) -> wx.Window
        
        Returns the page specified by the given index.
        """
        ...
    
    def GetPageBitmap(self, page):
        """
        GetPageBitmap(page) -> wx.Bitmap
        
        Returns the tab bitmap for the page.
        """
        ...
    
    def GetPageCount(self):
        """
        GetPageCount() -> size_t
        
        Returns the number of pages in the notebook.
        """
        ...
    
    def GetPageIndex(self, page_wnd):
        """
        GetPageIndex(page_wnd) -> int
        
        Returns the page index for the specified window.
        """
        ...
    
    def GetPageText(self, page):
        """
        GetPageText(page) -> String
        
        Returns the tab label for the page.
        """
        ...
    
    def GetPageToolTip(self, pageIdx):
        """
        GetPageToolTip(pageIdx) -> String
        
        Returns the tooltip for the tab label of the page.
        """
        ...
    
    def GetSelection(self):
        """
        GetSelection() -> int
        
        Returns the currently selected page.
        """
        ...
    
    def GetTabCtrlHeight(self):
        """
        GetTabCtrlHeight() -> int
        
        Returns the height of the tab control.
        """
        ...
    
    def InsertPage(self, *args, **kw):
        """
        InsertPage(page_idx, page, caption, select=False, bitmap=wx.BitmapBundle()) -> bool
        InsertPage(index, page, text, select, imageId) -> bool
        
        InsertPage() is similar to AddPage, but allows the ability to specify
        the insert location.
        """
        ...
    
    def RemovePage(self, page):
        """
        RemovePage(page) -> bool
        
        Removes a page, without deleting the window pointer.
        """
        ...
    
    def SetArtProvider(self, art):
        """
        SetArtProvider(art)
        
        Sets the art provider to be used by the notebook.
        """
        ...
    
    def SetFont(self, font):
        """
        SetFont(font) -> bool
        
        Sets the font for drawing the tab labels, using a bold version of the
        font for selected tab labels.
        """
        ...
    
    def SetMeasuringFont(self, font):
        """
        SetMeasuringFont(font)
        
        Sets the font for measuring tab labels.
        """
        ...
    
    def SetNormalFont(self, font):
        """
        SetNormalFont(font)
        
        Sets the font for drawing unselected tab labels.
        """
        ...
    
    def SetPageBitmap(self, page, bitmap):
        """
        SetPageBitmap(page, bitmap) -> bool
        
        Sets the bitmap for the page.
        """
        ...
    
    def SetPageImage(self, n, imageId):
        """
        SetPageImage(n, imageId) -> bool
        
        Sets the image index for the given page.
        """
        ...
    
    def SetPageText(self, page, text):
        """
        SetPageText(page, text) -> bool
        
        Sets the tab label for the page.
        """
        ...
    
    def SetPageToolTip(self, page, text):
        """
        SetPageToolTip(page, text) -> bool
        
        Sets the tooltip displayed when hovering over the tab label of the
        page.
        """
        ...
    
    def SetSelectedFont(self, font):
        """
        SetSelectedFont(font)
        
        Sets the font for drawing selected tab labels.
        """
        ...
    
    def SetSelection(self, new_page):
        """
        SetSelection(new_page) -> int
        
        Sets the page selection.
        """
        ...
    
    def SetTabCtrlHeight(self, height):
        """
        SetTabCtrlHeight(height)
        
        Sets the tab height.
        """
        ...
    
    def SetUniformBitmapSize(self, size):
        """
        SetUniformBitmapSize(size)
        
        Ensure that all tabs have the same height, even if some of them don't
        have bitmaps.
        """
        ...
    
    def Split(self, page, direction):
        """
        Split(page, direction)
        
        Split performs a split operation programmatically.
        """
        ...
    
    def ShowWindowMenu(self):
        """
        ShowWindowMenu() -> bool
        
        Shows the window menu for the active tab control associated with this
        notebook, and returns true if a selection was made.
        """
        ...
    
    def GetPageImage(self, nPage):
        """
        GetPageImage(nPage) -> int
        
        Returns the image index for the given page.
        """
        ...
    
    def GetTabCtrlFromPoint(self, pt):
        """
        GetTabCtrlFromPoint(pt) -> AuiTabCtrl
        
        Returns tab control based on point coordinates inside the tab frame.
        """
        ...
    
    def GetActiveTabCtrl(self):
        """
        GetActiveTabCtrl() -> AuiTabCtrl
        
        Returns active tab control for this notebook.
        """
        ...
    
    def FindTab(self, page, ctrl, idx):
        """
        FindTab(page, ctrl, idx) -> bool
        
        Finds tab control associated with a given window and its tab index.
        """
        ...
    
    @staticmethod
    def GetClassDefaultAttributes(variant=...):
        """
        GetClassDefaultAttributes(variant=wx.WINDOW_VARIANT_NORMAL) -> wx.VisualAttributes
        """
        ...
    
    ActiveTabCtrl = ...
    ArtProvider = ...
    CurrentPage = ...
    PageCount = ...
    Selection = ...
    TabCtrlHeight = ...


class AuiNotebookPage:
    """
    A simple class which holds information about the notebook's pages and
    their state.
    """
    window = ...
    caption = ...
    tooltip = ...
    bitmap = ...
    rect = ...
    active = ...


class AuiTabContainerButton:
    """
    A simple class which holds information about wxAuiNotebook tab buttons
    and their state.
    """
    id = ...
    curState = ...
    location = ...
    bitmap = ...
    disBitmap = ...
    rect = ...


class AuiTabContainer:
    """
    AuiTabContainer()
    
    wxAuiTabContainer is a class which contains information about each
    tab.
    """
    def __init__(self) -> None:
        """
        AuiTabContainer()
        
        wxAuiTabContainer is a class which contains information about each
        tab.
        """
        ...
    
    def SetArtProvider(self, art):
        """
        SetArtProvider(art)
        """
        ...
    
    def GetArtProvider(self):
        """
        GetArtProvider() -> AuiTabArt
        """
        ...
    
    def SetFlags(self, flags):
        """
        SetFlags(flags)
        """
        ...
    
    def GetFlags(self):
        """
        GetFlags() -> unsignedint
        """
        ...
    
    def AddPage(self, page, info):
        """
        AddPage(page, info) -> bool
        """
        ...
    
    def InsertPage(self, page, info, idx):
        """
        InsertPage(page, info, idx) -> bool
        """
        ...
    
    def MovePage(self, page, newIdx):
        """
        MovePage(page, newIdx) -> bool
        """
        ...
    
    def RemovePage(self, page):
        """
        RemovePage(page) -> bool
        """
        ...
    
    def SetActivePage(self, *args, **kw):
        """
        SetActivePage(page) -> bool
        SetActivePage(page) -> bool
        """
        ...
    
    def SetNoneActive(self):
        """
        SetNoneActive()
        """
        ...
    
    def GetActivePage(self):
        """
        GetActivePage() -> int
        """
        ...
    
    def TabHitTest(self, x, y, hit):
        """
        TabHitTest(x, y, hit) -> bool
        """
        ...
    
    def ButtonHitTest(self, x, y, hit):
        """
        ButtonHitTest(x, y, hit) -> bool
        """
        ...
    
    def GetWindowFromIdx(self, idx):
        """
        GetWindowFromIdx(idx) -> wx.Window
        """
        ...
    
    def GetIdxFromWindow(self, page):
        """
        GetIdxFromWindow(page) -> int
        """
        ...
    
    def GetPageCount(self):
        """
        GetPageCount() -> size_t
        """
        ...
    
    def GetPage(self, idx):
        """
        GetPage(idx) -> AuiNotebookPage
        """
        ...
    
    def GetPages(self):
        """
        GetPages() -> AuiNotebookPageArray
        """
        ...
    
    def SetNormalFont(self, normalFont):
        """
        SetNormalFont(normalFont)
        """
        ...
    
    def SetSelectedFont(self, selectedFont):
        """
        SetSelectedFont(selectedFont)
        """
        ...
    
    def SetMeasuringFont(self, measuringFont):
        """
        SetMeasuringFont(measuringFont)
        """
        ...
    
    def SetColour(self, colour):
        """
        SetColour(colour)
        """
        ...
    
    def SetActiveColour(self, colour):
        """
        SetActiveColour(colour)
        """
        ...
    
    def DoShowHide(self):
        """
        DoShowHide()
        """
        ...
    
    def SetRect(self, rect, wnd=...):
        """
        SetRect(rect, wnd=None)
        """
        ...
    
    def RemoveButton(self, id):
        """
        RemoveButton(id)
        """
        ...
    
    def AddButton(self, id, location, normalBitmap=..., disabledBitmap=...):
        """
        AddButton(id, location, normalBitmap=wx.BitmapBundle(), disabledBitmap=wx.BitmapBundle())
        """
        ...
    
    def GetTabOffset(self):
        """
        GetTabOffset() -> size_t
        """
        ...
    
    def SetTabOffset(self, offset):
        """
        SetTabOffset(offset)
        """
        ...
    
    def IsTabVisible(self, tabPage, tabOffset, dc, wnd):
        """
        IsTabVisible(tabPage, tabOffset, dc, wnd) -> bool
        """
        ...
    
    def MakeTabVisible(self, tabPage, win):
        """
        MakeTabVisible(tabPage, win)
        """
        ...
    
    ActivePage = ...
    ArtProvider = ...
    Flags = ...
    PageCount = ...
    Pages = ...
    TabOffset = ...


class AuiTabArt:
    """
    AuiTabArt()
    
    Tab art provider defines all the drawing functions used by
    wxAuiNotebook.
    """
    def __init__(self) -> None:
        """
        AuiTabArt()
        
        Tab art provider defines all the drawing functions used by
        wxAuiNotebook.
        """
        ...
    
    def Clone(self):
        """
        Clone() -> AuiTabArt
        
        Clones the art object.
        """
        ...
    
    def DrawBackground(self, dc, wnd, rect):
        """
        DrawBackground(dc, wnd, rect)
        
        Draws a background on the given area.
        """
        ...
    
    def DrawButton(self, dc, wnd, in_rect, bitmap_id, button_state, orientation, out_rect):
        """
        DrawButton(dc, wnd, in_rect, bitmap_id, button_state, orientation, out_rect)
        
        Draws a button.
        """
        ...
    
    def DrawTab(self, dc, wnd, page, rect, close_button_state, out_tab_rect, out_button_rect, x_extent):
        """
        DrawTab(dc, wnd, page, rect, close_button_state, out_tab_rect, out_button_rect, x_extent)
        
        Draws a tab.
        """
        ...
    
    def GetBestTabCtrlSize(self, /, /):
        """
        GetBestTabCtrlSize(, , ) -> int
        
        Returns the tab control size.
        """
        ...
    
    def GetIndentSize(self):
        """
        GetIndentSize() -> int
        
        Returns the indent size.
        """
        ...
    
    def GetTabSize(self, dc, wnd, caption, bitmap, active, close_button_state, x_extent):
        """
        GetTabSize(dc, wnd, caption, bitmap, active, close_button_state, x_extent) -> wx.Size
        
        Returns the tab size for the given caption, bitmap and state.
        """
        ...
    
    def SetFlags(self, flags):
        """
        SetFlags(flags)
        
        Sets flags.
        """
        ...
    
    def SetMeasuringFont(self, font):
        """
        SetMeasuringFont(font)
        
        Sets the font used for calculating measurements.
        """
        ...
    
    def SetNormalFont(self, font):
        """
        SetNormalFont(font)
        
        Sets the normal font for drawing labels.
        """
        ...
    
    def SetSelectedFont(self, font):
        """
        SetSelectedFont(font)
        
        Sets the font for drawing text for selected UI elements.
        """
        ...
    
    def SetColour(self, colour):
        """
        SetColour(colour)
        
        Sets the colour of the inactive tabs.
        """
        ...
    
    def SetActiveColour(self, colour):
        """
        SetActiveColour(colour)
        
        Sets the colour of the selected tab.
        """
        ...
    
    def SetSizingInfo(self, tab_ctrl_size, tab_count, wnd=...):
        """
        SetSizingInfo(tab_ctrl_size, tab_count, wnd=None)
        
        Sets sizing information.
        """
        ...
    
    IndentSize = ...


class AuiDefaultTabArt(AuiTabArt):
    """
    AuiDefaultTabArt()
    
    Default art provider for wxAuiNotebook.
    """
    def __init__(self) -> None:
        """
        AuiDefaultTabArt()
        
        Default art provider for wxAuiNotebook.
        """
        ...
    
    def Clone(self):
        """
        Clone() -> AuiTabArt
        
        Clones the art object.
        """
        ...
    
    def SetFlags(self, flags):
        """
        SetFlags(flags)
        
        Sets flags.
        """
        ...
    
    def SetSizingInfo(self, tab_ctrl_size, tab_count, wnd=...):
        """
        SetSizingInfo(tab_ctrl_size, tab_count, wnd=None)
        
        Sets sizing information.
        """
        ...
    
    def SetNormalFont(self, font):
        """
        SetNormalFont(font)
        
        Sets the normal font for drawing labels.
        """
        ...
    
    def SetSelectedFont(self, font):
        """
        SetSelectedFont(font)
        
        Sets the font for drawing text for selected UI elements.
        """
        ...
    
    def SetMeasuringFont(self, font):
        """
        SetMeasuringFont(font)
        
        Sets the font used for calculating measurements.
        """
        ...
    
    def SetColour(self, colour):
        """
        SetColour(colour)
        
        Sets the colour of the inactive tabs.
        """
        ...
    
    def SetActiveColour(self, colour):
        """
        SetActiveColour(colour)
        
        Sets the colour of the selected tab.
        """
        ...
    
    def DrawBackground(self, dc, wnd, rect):
        """
        DrawBackground(dc, wnd, rect)
        
        Draws a background on the given area.
        """
        ...
    
    def DrawTab(self, dc, wnd, page, rect, close_button_state, out_tab_rect, out_button_rect, x_extent):
        """
        DrawTab(dc, wnd, page, rect, close_button_state, out_tab_rect, out_button_rect, x_extent)
        
        Draws a tab.
        """
        ...
    
    def DrawButton(self, dc, wnd, in_rect, bitmap_id, button_state, orientation, out_rect):
        """
        DrawButton(dc, wnd, in_rect, bitmap_id, button_state, orientation, out_rect)
        
        Draws a button.
        """
        ...
    
    def GetIndentSize(self):
        """
        GetIndentSize() -> int
        
        Returns the indent size.
        """
        ...
    
    def GetTabSize(self, dc, wnd, caption, bitmap, active, close_button_state, x_extent):
        """
        GetTabSize(dc, wnd, caption, bitmap, active, close_button_state, x_extent) -> wx.Size
        
        Returns the tab size for the given caption, bitmap and state.
        """
        ...
    
    def ShowDropDown(self, wnd, items, activeIdx):
        """
        ShowDropDown(wnd, items, activeIdx) -> int
        """
        ...
    
    def GetBestTabCtrlSize(self, /, /):
        """
        GetBestTabCtrlSize(, , ) -> int
        
        Returns the tab control size.
        """
        ...
    
    IndentSize = ...


class AuiSimpleTabArt(AuiTabArt):
    """
    AuiSimpleTabArt()
    
    Another standard tab art provider for wxAuiNotebook.
    """
    def __init__(self) -> None:
        """
        AuiSimpleTabArt()
        
        Another standard tab art provider for wxAuiNotebook.
        """
        ...
    
    def Clone(self):
        """
        Clone() -> AuiTabArt
        
        Clones the art object.
        """
        ...
    
    def SetFlags(self, flags):
        """
        SetFlags(flags)
        
        Sets flags.
        """
        ...
    
    def SetSizingInfo(self, tab_ctrl_size, tab_count, wnd=...):
        """
        SetSizingInfo(tab_ctrl_size, tab_count, wnd=None)
        
        Sets sizing information.
        """
        ...
    
    def SetNormalFont(self, font):
        """
        SetNormalFont(font)
        
        Sets the normal font for drawing labels.
        """
        ...
    
    def SetSelectedFont(self, font):
        """
        SetSelectedFont(font)
        
        Sets the font for drawing text for selected UI elements.
        """
        ...
    
    def SetMeasuringFont(self, font):
        """
        SetMeasuringFont(font)
        
        Sets the font used for calculating measurements.
        """
        ...
    
    def SetColour(self, colour):
        """
        SetColour(colour)
        
        Sets the colour of the inactive tabs.
        """
        ...
    
    def SetActiveColour(self, colour):
        """
        SetActiveColour(colour)
        
        Sets the colour of the selected tab.
        """
        ...
    
    def DrawBackground(self, dc, wnd, rect):
        """
        DrawBackground(dc, wnd, rect)
        
        Draws a background on the given area.
        """
        ...
    
    def DrawTab(self, dc, wnd, page, rect, close_button_state, out_tab_rect, out_button_rect, x_extent):
        """
        DrawTab(dc, wnd, page, rect, close_button_state, out_tab_rect, out_button_rect, x_extent)
        
        Draws a tab.
        """
        ...
    
    def DrawButton(self, dc, wnd, in_rect, bitmap_id, button_state, orientation, out_rect):
        """
        DrawButton(dc, wnd, in_rect, bitmap_id, button_state, orientation, out_rect)
        
        Draws a button.
        """
        ...
    
    def GetIndentSize(self):
        """
        GetIndentSize() -> int
        
        Returns the indent size.
        """
        ...
    
    def GetTabSize(self, dc, wnd, caption, bitmap, active, closeButtonState, xExtent):
        """
        GetTabSize(dc, wnd, caption, bitmap, active, closeButtonState, xExtent) -> wx.Size
        """
        ...
    
    def ShowDropDown(self, wnd, items, activeIdx):
        """
        ShowDropDown(wnd, items, activeIdx) -> int
        """
        ...
    
    def GetBestTabCtrlSize(self, /, /):
        """
        GetBestTabCtrlSize(, , ) -> int
        
        Returns the tab control size.
        """
        ...
    
    IndentSize = ...


class AuiNotebookEvent(wx.BookCtrlEvent):
    """
    AuiNotebookEvent(command_type=wx.wxEVT_NULL, win_id=0)
    
    This class is used by the events generated by wxAuiNotebook.
    """
    def __init__(self, command_type=..., win_id=...) -> None:
        """
        AuiNotebookEvent(command_type=wx.wxEVT_NULL, win_id=0)
        
        This class is used by the events generated by wxAuiNotebook.
        """
        ...
    
    def Clone(self):
        """
        Clone() -> wx.Event
        """
        ...
    


EVT_AUINOTEBOOK_PAGE_CLOSE = ...
EVT_AUINOTEBOOK_PAGE_CLOSED = ...
EVT_AUINOTEBOOK_PAGE_CHANGED = ...
EVT_AUINOTEBOOK_PAGE_CHANGING = ...
EVT_AUINOTEBOOK_BUTTON = ...
EVT_AUINOTEBOOK_BEGIN_DRAG = ...
EVT_AUINOTEBOOK_END_DRAG = ...
EVT_AUINOTEBOOK_DRAG_MOTION = ...
EVT_AUINOTEBOOK_ALLOW_DND = ...
EVT_AUINOTEBOOK_DRAG_DONE = ...
EVT_AUINOTEBOOK_TAB_MIDDLE_DOWN = ...
EVT_AUINOTEBOOK_TAB_MIDDLE_UP = ...
EVT_AUINOTEBOOK_TAB_RIGHT_DOWN = ...
EVT_AUINOTEBOOK_TAB_RIGHT_UP = ...
EVT_AUINOTEBOOK_BG_DCLICK = ...
class AuiTabCtrl(wx.Control, AuiTabContainer):
    """
    AuiTabCtrl(parent, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, style=0)
    """
    def __init__(self, parent, id=..., pos=..., size=..., style=...) -> None:
        """
        AuiTabCtrl(parent, id=wx.ID_ANY, pos=wx.DefaultPosition, size=wx.DefaultSize, style=0)
        """
        ...
    
    def IsDragging(self):
        """
        IsDragging() -> bool
        """
        ...
    
    @staticmethod
    def GetClassDefaultAttributes(variant=...):
        """
        GetClassDefaultAttributes(variant=wx.WINDOW_VARIANT_NORMAL) -> wx.VisualAttributes
        """
        ...
    


class AuiMDIParentFrame(wx.Frame):
    """
    AuiMDIParentFrame()
    AuiMDIParentFrame(parent, winid=wx.ID_ANY, title=wx.EmptyString, pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.DEFAULT_FRAME_STYLE|wx.VSCROLL|wx.HSCROLL, name=wx.FrameNameStr)
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiMDIParentFrame()
        AuiMDIParentFrame(parent, winid=wx.ID_ANY, title=wx.EmptyString, pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.DEFAULT_FRAME_STYLE|wx.VSCROLL|wx.HSCROLL, name=wx.FrameNameStr)
        """
        ...
    
    def Create(self, parent, winid=..., title=..., pos=..., size=..., style=..., name=...):
        """
        Create(parent, winid=wx.ID_ANY, title=wx.EmptyString, pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.DEFAULT_FRAME_STYLE|wx.VSCROLL|wx.HSCROLL, name=wx.FrameNameStr) -> bool
        """
        ...
    
    def SetArtProvider(self, provider):
        """
        SetArtProvider(provider)
        """
        ...
    
    def GetArtProvider(self):
        """
        GetArtProvider() -> AuiTabArt
        """
        ...
    
    def GetNotebook(self):
        """
        GetNotebook() -> AuiNotebook
        """
        ...
    
    def GetWindowMenu(self):
        """
        GetWindowMenu() -> wx.Menu
        """
        ...
    
    def SetWindowMenu(self, pMenu):
        """
        SetWindowMenu(pMenu)
        """
        ...
    
    def SetMenuBar(self, menuBar):
        """
        SetMenuBar(menuBar)
        
        Tells the frame to show the given menu bar.
        """
        ...
    
    def SetChildMenuBar(self, pChild):
        """
        SetChildMenuBar(pChild)
        """
        ...
    
    def GetActiveChild(self):
        """
        GetActiveChild() -> AuiMDIChildFrame
        """
        ...
    
    def SetActiveChild(self, pChildFrame):
        """
        SetActiveChild(pChildFrame)
        """
        ...
    
    def GetClientWindow(self):
        """
        GetClientWindow() -> AuiMDIClientWindow
        """
        ...
    
    def OnCreateClient(self):
        """
        OnCreateClient() -> AuiMDIClientWindow
        """
        ...
    
    def Cascade(self):
        """
        Cascade()
        """
        ...
    
    def Tile(self, orient=...):
        """
        Tile(orient=wx.HORIZONTAL)
        """
        ...
    
    def ArrangeIcons(self):
        """
        ArrangeIcons()
        """
        ...
    
    def ActivateNext(self):
        """
        ActivateNext()
        """
        ...
    
    def ActivatePrevious(self):
        """
        ActivatePrevious()
        """
        ...
    
    @staticmethod
    def GetClassDefaultAttributes(variant=...):
        """
        GetClassDefaultAttributes(variant=wx.WINDOW_VARIANT_NORMAL) -> wx.VisualAttributes
        """
        ...
    
    ActiveChild = ...
    ArtProvider = ...
    ClientWindow = ...
    Notebook = ...
    WindowMenu = ...


class AuiMDIChildFrame(TDIChildFrame):
    """
    AuiMDIChildFrame()
    AuiMDIChildFrame(parent, winid=wx.ID_ANY, title=wx.EmptyString, pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.DEFAULT_FRAME_STYLE, name=wx.FrameNameStr)
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiMDIChildFrame()
        AuiMDIChildFrame(parent, winid=wx.ID_ANY, title=wx.EmptyString, pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.DEFAULT_FRAME_STYLE, name=wx.FrameNameStr)
        """
        ...
    
    def Create(self, parent, winid=..., title=..., pos=..., size=..., style=..., name=...):
        """
        Create(parent, winid=wx.ID_ANY, title=wx.EmptyString, pos=wx.DefaultPosition, size=wx.DefaultSize, style=wx.DEFAULT_FRAME_STYLE, name=wx.FrameNameStr) -> bool
        """
        ...
    
    def SetMenuBar(self, menuBar):
        """
        SetMenuBar(menuBar)
        """
        ...
    
    def GetMenuBar(self):
        """
        GetMenuBar() -> wx.MenuBar
        """
        ...
    
    def SetTitle(self, title):
        """
        SetTitle(title)
        """
        ...
    
    def GetTitle(self):
        """
        GetTitle() -> String
        """
        ...
    
    def SetIcons(self, icons):
        """
        SetIcons(icons)
        """
        ...
    
    def GetIcons(self):
        """
        GetIcons() -> wx.IconBundle
        """
        ...
    
    def SetIcon(self, icon):
        """
        SetIcon(icon)
        """
        ...
    
    def GetIcon(self):
        """
        GetIcon() -> wx.Icon
        """
        ...
    
    def Activate(self):
        """
        Activate()
        """
        ...
    
    def Destroy(self):
        """
        Destroy() -> bool
        
        Destroys the window safely.
        """
        ...
    
    def Show(self, show=...):
        """
        Show(show=True) -> bool
        
        Shows or hides the window.
        """
        ...
    
    def CreateStatusBar(self, number=..., style=..., winid=..., name=...):
        """
        CreateStatusBar(number=1, style=1, winid=1, name=wx.EmptyString) -> wx.StatusBar
        """
        ...
    
    def GetStatusBar(self):
        """
        GetStatusBar() -> wx.StatusBar
        """
        ...
    
    def SetStatusText(self, text, number=...):
        """
        SetStatusText(text, number=0)
        """
        ...
    
    def SetStatusWidths(self, widths):
        """
        SetStatusWidths(widths)
        """
        ...
    
    def CreateToolBar(self, style, winid, name):
        """
        CreateToolBar(style, winid, name) -> wx.ToolBar
        """
        ...
    
    def GetToolBar(self):
        """
        GetToolBar() -> wx.ToolBar
        """
        ...
    
    def Maximize(self, maximize=...):
        """
        Maximize(maximize=True)
        """
        ...
    
    def Restore(self):
        """
        Restore()
        """
        ...
    
    def Iconize(self, iconize=...):
        """
        Iconize(iconize=True)
        """
        ...
    
    def IsMaximized(self):
        """
        IsMaximized() -> bool
        """
        ...
    
    def IsIconized(self):
        """
        IsIconized() -> bool
        """
        ...
    
    def ShowFullScreen(self, show, style):
        """
        ShowFullScreen(show, style) -> bool
        """
        ...
    
    def IsFullScreen(self):
        """
        IsFullScreen() -> bool
        """
        ...
    
    def IsTopLevel(self):
        """
        IsTopLevel() -> bool
        
        Returns true if the given window is a top-level one.
        """
        ...
    
    def SetMDIParentFrame(self, parent):
        """
        SetMDIParentFrame(parent)
        """
        ...
    
    def GetMDIParentFrame(self):
        """
        GetMDIParentFrame() -> AuiMDIParentFrame
        """
        ...
    
    @staticmethod
    def GetClassDefaultAttributes(variant=...):
        """
        GetClassDefaultAttributes(variant=wx.WINDOW_VARIANT_NORMAL) -> wx.VisualAttributes
        """
        ...
    
    Icon = ...
    Icons = ...
    MDIParentFrame = ...
    MenuBar = ...
    StatusBar = ...
    Title = ...
    ToolBar = ...


class AuiMDIClientWindow(AuiNotebook):
    """
    AuiMDIClientWindow()
    AuiMDIClientWindow(parent, style=0)
    """
    def __init__(self, *args, **kw) -> None:
        """
        AuiMDIClientWindow()
        AuiMDIClientWindow(parent, style=0)
        """
        ...
    
    def CreateClient(self, parent, style=...):
        """
        CreateClient(parent, style=wx.VSCROLL|wx.HSCROLL) -> bool
        """
        ...
    
    def SetSelection(self, new_page):
        """
        SetSelection(new_page) -> int
        
        Sets the page selection.
        """
        ...
    
    def GetActiveChild(self):
        """
        GetActiveChild() -> AuiMDIChildFrame
        """
        ...
    
    def SetActiveChild(self, pChildFrame):
        """
        SetActiveChild(pChildFrame)
        """
        ...
    
    @staticmethod
    def GetClassDefaultAttributes(variant=...):
        """
        GetClassDefaultAttributes(variant=wx.WINDOW_VARIANT_NORMAL) -> wx.VisualAttributes
        """
        ...
    
    ActiveChild = ...


