"""
This type stub file was generated by pyright.
"""

"""
These classes enable viewing and interacting with an OpenGL context in a wx.Window.
"""
WX_GL_RGBA = ...
WX_GL_BUFFER_SIZE = ...
WX_GL_LEVEL = ...
WX_GL_DOUBLEBUFFER = ...
WX_GL_STEREO = ...
WX_GL_AUX_BUFFERS = ...
WX_GL_MIN_RED = ...
WX_GL_MIN_GREEN = ...
WX_GL_MIN_BLUE = ...
WX_GL_MIN_ALPHA = ...
WX_GL_DEPTH_SIZE = ...
WX_GL_STENCIL_SIZE = ...
WX_GL_MIN_ACCUM_RED = ...
WX_GL_MIN_ACCUM_GREEN = ...
WX_GL_MIN_ACCUM_BLUE = ...
WX_GL_MIN_ACCUM_ALPHA = ...
WX_GL_SAMPLE_BUFFERS = ...
WX_GL_SAMPLES = ...
WX_GL_FRAMEBUFFER_SRGB = ...
WX_GL_MAJOR_VERSION = ...
WX_GL_MINOR_VERSION = ...
WX_GL_CORE_PROFILE = ...
_GL_COMPAT_PROFILE = ...
WX_GL_FORWARD_COMPAT = ...
WX_GL_ES2 = ...
WX_GL_DEBUG = ...
WX_GL_ROBUST_ACCESS = ...
WX_GL_NO_RESET_NOTIFY = ...
WX_GL_LOSE_ON_RESET = ...
WX_GL_RESET_ISOLATION = ...
WX_GL_RELEASE_FLUSH = ...
WX_GL_RELEASE_NONE = ...
class GLAttribsBase:
    """
    GLAttribsBase()
    
    This is the base class for wxGLAttributes and wxGLContextAttrs.
    """
    def __init__(self) -> None:
        """
        GLAttribsBase()
        
        This is the base class for wxGLAttributes and wxGLContextAttrs.
        """
        ...
    
    def AddAttribute(self, attribute):
        """
        AddAttribute(attribute)
        
        Adds an integer value to the list of attributes.
        """
        ...
    
    def AddAttribBits(self, searchVal, combineVal):
        """
        AddAttribBits(searchVal, combineVal)
        
        Combine (bitwise OR) a given value with the existing one, if any.
        """
        ...
    
    def SetNeedsARB(self, needsARB=...):
        """
        SetNeedsARB(needsARB=True)
        
        Sets the necessity of using special ARB-functions (e.g.
        """
        ...
    
    def Reset(self):
        """
        Reset()
        
        Delete contents and sets ARB-flag to false.
        """
        ...
    
    def GetSize(self):
        """
        GetSize() -> int
        
        Returns the size of the internal list of attributes.
        """
        ...
    
    def NeedsARB(self):
        """
        NeedsARB() -> bool
        
        Returns the current value of the ARB-flag.
        """
        ...
    
    Size = ...


class GLAttributes(GLAttribsBase):
    """
    This class is used for setting display attributes when drawing through
    OpenGL ("Pixel format" in MSW and OSX parlance, "Configs" in X11).
    """
    def RGBA(self):
        """
        RGBA() -> GLAttributes
        
        Use true colour instead of colour index rendering for each pixel.
        """
        ...
    
    def BufferSize(self, val):
        """
        BufferSize(val) -> GLAttributes
        
        Specifies the number of bits for colour buffer.
        """
        ...
    
    def Level(self, val):
        """
        Level(val) -> GLAttributes
        
        Specifies the framebuffer level.
        """
        ...
    
    def DoubleBuffer(self):
        """
        DoubleBuffer() -> GLAttributes
        
        Requests using double buffering.
        """
        ...
    
    def Stereo(self):
        """
        Stereo() -> GLAttributes
        
        Use stereoscopic display.
        """
        ...
    
    def AuxBuffers(self, val):
        """
        AuxBuffers(val) -> GLAttributes
        
        Specifies the number of auxiliary buffers.
        """
        ...
    
    def MinRGBA(self, mRed, mGreen, mBlue, mAlpha):
        """
        MinRGBA(mRed, mGreen, mBlue, mAlpha) -> GLAttributes
        
        Specifies the minimal number of bits for each colour and alpha.
        """
        ...
    
    def Depth(self, val):
        """
        Depth(val) -> GLAttributes
        
        Specifies number of bits for Z-buffer.
        """
        ...
    
    def Stencil(self, val):
        """
        Stencil(val) -> GLAttributes
        
        Specifies number of bits for stencil buffer.
        """
        ...
    
    def MinAcumRGBA(self, mRed, mGreen, mBlue, mAlpha):
        """
        MinAcumRGBA(mRed, mGreen, mBlue, mAlpha) -> GLAttributes
        
        Specifies the minimal number of bits for each accumulator channel.
        """
        ...
    
    def SampleBuffers(self, val):
        """
        SampleBuffers(val) -> GLAttributes
        
        Use multi-sampling support (antialiasing).
        """
        ...
    
    def Samplers(self, val):
        """
        Samplers(val) -> GLAttributes
        
        Specifies the number of samplers per pixel.
        """
        ...
    
    def FrameBuffersRGB(self):
        """
        FrameBuffersRGB() -> GLAttributes
        
        Used to request a frame buffer sRGB capable.
        """
        ...
    
    def PlatformDefaults(self):
        """
        PlatformDefaults() -> GLAttributes
        
        Set some typically needed attributes.
        """
        ...
    
    def Defaults(self):
        """
        Defaults() -> GLAttributes
        
        wxWidgets defaults: RGBA, Z-depth 16 bits, double buffering, 1 sample
        buffer, 4 samplers.
        """
        ...
    
    def EndList(self):
        """
        EndList()
        
        The set of attributes must end with this one; otherwise, the GPU may
        display nothing at all.
        """
        ...
    


class GLContextAttrs(GLAttribsBase):
    """
    This class is used for setting context attributes.
    """
    def CoreProfile(self):
        """
        CoreProfile() -> GLContextAttrs
        
        Request an OpenGL core profile for the context.
        """
        ...
    
    def MajorVersion(self, val):
        """
        MajorVersion(val) -> GLContextAttrs
        
        Request specific OpenGL core major version number (>= 3).
        """
        ...
    
    def MinorVersion(self, val):
        """
        MinorVersion(val) -> GLContextAttrs
        
        Request specific OpenGL core minor version number.
        """
        ...
    
    def OGLVersion(self, vmayor, vminor):
        """
        OGLVersion(vmayor, vminor) -> GLContextAttrs
        
        An easy way of requesting an OpenGL version.
        """
        ...
    
    def CompatibilityProfile(self):
        """
        CompatibilityProfile() -> GLContextAttrs
        
        Request a type of context with all OpenGL features from version 1.0 to
        the newest available by the GPU driver.
        """
        ...
    
    def ForwardCompatible(self):
        """
        ForwardCompatible() -> GLContextAttrs
        
        Request a forward-compatible context.
        """
        ...
    
    def ES2(self):
        """
        ES2() -> GLContextAttrs
        
        Request an ES or ES2 ("Embedded Subsystem") context.
        """
        ...
    
    def DebugCtx(self):
        """
        DebugCtx() -> GLContextAttrs
        
        Request debugging functionality.
        """
        ...
    
    def Robust(self):
        """
        Robust() -> GLContextAttrs
        
        Request robustness, or how OpenGL handles out-of-bounds buffer object
        accesses and graphics reset notification behaviours.
        """
        ...
    
    def NoResetNotify(self):
        """
        NoResetNotify() -> GLContextAttrs
        
        With robustness enabled, never deliver notification of reset events.
        """
        ...
    
    def LoseOnReset(self):
        """
        LoseOnReset() -> GLContextAttrs
        
        With robustness enabled, if graphics reset happens, all context state
        is lost.
        """
        ...
    
    def ResetIsolation(self):
        """
        ResetIsolation() -> GLContextAttrs
        
        Request OpenGL to protect other applications or shared contexts from
        reset side-effects.
        """
        ...
    
    def ReleaseFlush(self, val=...):
        """
        ReleaseFlush(val=1) -> GLContextAttrs
        
        Request OpenGL to avoid or not flushing pending commands when the
        context is made no longer current (released).
        """
        ...
    
    def PlatformDefaults(self):
        """
        PlatformDefaults() -> GLContextAttrs
        
        Set platform specific defaults.
        """
        ...
    
    def EndList(self):
        """
        EndList()
        
        The set of attributes must end with this one; otherwise, the GPU may
        display nothing at all.
        """
        ...
    


class GLContext(Object):
    """
    GLContext(win, other=None, ctxAttrs=None)
    
    An instance of a wxGLContext represents the state of an OpenGL state
    machine and the connection between OpenGL and the system.
    """
    def __init__(self, win, other=..., ctxAttrs=...) -> None:
        """
        GLContext(win, other=None, ctxAttrs=None)
        
        An instance of a wxGLContext represents the state of an OpenGL state
        machine and the connection between OpenGL and the system.
        """
        ...
    
    def IsOK(self):
        """
        IsOK() -> bool
        
        Checks if the underlying OpenGL rendering context was correctly
        created by the system with the requested attributes.
        """
        ...
    
    def SetCurrent(self, win):
        """
        SetCurrent(win) -> bool
        
        Makes the OpenGL state that is represented by this rendering context
        current with the wxGLCanvas win.
        """
        ...
    


class GLCanvas(Window):
    """
    GLCanvas(parent, dispAttrs, id=ID_ANY, pos=DefaultPosition, size=DefaultSize, style=0, name=GLCanvasName, palette=NullPalette)
    GLCanvas(parent, id=wx.ID_ANY, attribList=None, pos=wx.DefaultPosition, size=wx.DefaultSize, style=0, name='GLCanvas', palette=wx.NullPalette)
    
    wxGLCanvas is a class for displaying OpenGL graphics.
    """
    def __init__(self, *args, **kw) -> None:
        """
        GLCanvas(parent, dispAttrs, id=ID_ANY, pos=DefaultPosition, size=DefaultSize, style=0, name=GLCanvasName, palette=NullPalette)
        GLCanvas(parent, id=wx.ID_ANY, attribList=None, pos=wx.DefaultPosition, size=wx.DefaultSize, style=0, name='GLCanvas', palette=wx.NullPalette)
        
        wxGLCanvas is a class for displaying OpenGL graphics.
        """
        ...
    
    def CreateSurface(self):
        """
        CreateSurface() -> bool
        
        Re-creates EGLSurface.
        """
        ...
    
    def SetColour(self, colour):
        """
        SetColour(colour) -> bool
        
        Sets the current colour for this window (using glcolor3f()), using the
        wxWidgets colour database to find a named colour.
        """
        ...
    
    def SetCurrent(self, context):
        """
        SetCurrent(context) -> bool
        
        Makes the OpenGL state that is represented by the OpenGL rendering
        context context current, i.e.
        """
        ...
    
    def SwapBuffers(self):
        """
        SwapBuffers() -> bool
        
        Swaps the double-buffer of this window, making the back-buffer the
        front-buffer and vice versa, so that the output of the previous OpenGL
        commands is displayed on the window.
        """
        ...
    
    @staticmethod
    def IsDisplaySupported(*args, **kw):
        """
        IsDisplaySupported(dispAttrs) -> bool
        IsDisplaySupported(attribList) -> bool
        
        Determines if a canvas having the specified attributes is available.
        """
        ...
    
    @staticmethod
    def IsExtensionSupported(extension):
        """
        IsExtensionSupported(extension) -> bool
        
        Returns true if the extension with given name is supported.
        """
        ...
    
    @staticmethod
    def GetClassDefaultAttributes(variant=...):
        """
        GetClassDefaultAttributes(variant=WINDOW_VARIANT_NORMAL) -> VisualAttributes
        """
        ...
    


USE_GLCANVAS = ...
