"""
This type stub file was generated by pyright.
"""

import wx

"""
This module contains a few classes that are only available on Windows.
"""
Metafile = ...
MetafileDC = ...
class PyAxBaseWindow(wx.Window):
    """
    PyAxBaseWindow(parent, id=-1, pos=wx.DefaultPosition, size=wx.DefaultSize, style=0, name=wx.PanelNameStr)
    PyAxBaseWindow()
    
    A Window class for use with ActiveX controls.
    
    This Window class exposes some low-level Microsoft Windows
    specific methods which can be overridden in Python.  Intended for
    use as an ActiveX container, but could also be useful
    elsewhere.
    """
    def __init__(self, *args, **kw) -> None:
        """
        PyAxBaseWindow(parent, id=-1, pos=wx.DefaultPosition, size=wx.DefaultSize, style=0, name=wx.PanelNameStr)
        PyAxBaseWindow()
        
        A Window class for use with ActiveX controls.
        
        This Window class exposes some low-level Microsoft Windows
        specific methods which can be overridden in Python.  Intended for
        use as an ActiveX container, but could also be useful
        elsewhere.
        """
        ...
    
    def MSWTranslateMessage(self, msg):
        """
        MSWTranslateMessage(msg) -> bool
        """
        ...
    


