---
name: Assign Milestone

on:
  pull_request:
#   pull_request_target:
#     types: [closed]

jobs:
  assign-milestone:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged || true
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - run: gh pr view ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
      - run: gh pr view ${{ github.event.pull_request.html_url }} --json milestone
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
      - name: Show VERSION file
        run: |
          gh api \
            -H "Accept: application/vnd.github.raw" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/{owner}/{repo}/contents/include/VERSION"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
      - name: Get VERSION file
        id: version-file
        run: |
          echo 'version<<EOF' >> "${GITHUB_OUTPUT}"
          gh api \
            -H "Accept: application/vnd.github.raw" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/{owner}/{repo}/contents/include/VERSION" >> "${GITHUB_OUTPUT}"
          echo 'EOF' >> "${GITHUB_OUTPUT}"
        # head -n 3 | xargs | sed 's/ /./g' | sed 's/\(RC\|dev\)//g'
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
      - run: echo $VERSIONFILE
        env:
          VERSIONFILE: ${{ steps.version-file.outputs.version}}
      - name: Get milestone title from VERSION file
        id: version
        run: |
          version=$(head -n 3 $VERSIONFILE | xargs | sed 's/ /./g' | sed 's/\(RC\|dev\)//g')
          echo "version=$version" >> "${GITHUB_OUTPUT}"
        env:
          VERSIONFILE: ${{ steps.version-file.outputs.version}}
      - run: echo $VERSION
        env:
          VERSION: ${{ steps.version.outputs.version }}

      # - uses: actions/github-script@v7
      #   with:
      #     script: |
      #       github.rest.issues.addLabels({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         labels: ['Triage']
      #       })
